### ISSUE TITLE
ElementNode -> isFixedPosition

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1338]
In some cases we may want to have documents that resemble a sort of template. For example, the first line always being a title while the rest of the document is just a normal body.

We already support half of this feature by having a BootstrapPlugin that supports custom a custom initialization function, but to fully support this, we have to make sure that the title node can't be removed later.

The API could possibly look like that (kudos to @trueadm for the proposal):
```
class ElementNode {
  isFixedPosition(): boolean;
}
```

**Comment by EgonBolton** [comment]
Interesting!
What do you think of the Prosemirror API for defining Schemas? https://prosemirror.net/docs/guide/#schema

It seems more flexible as you can define crazier things like: "I don't want more than 5 paragraphs in a row without a title in the middle" (one of the rules I have for writers at my SEO agency).

**Comment by nvegater** [comment]
> What do you think of the Prosemirror API for defining Schemas?

My two cents: Very flexible but I don't think is very "react-like". The schema Object is okay, but I hope Lexical comes up with something better.
For example, a Schema FC component that takes React components as attributes, that way we can pass props to the different parts of the schema. 
I think that this would be a better DX because it makes it easy to add things like dynamic templates.

**Comment by thegreatercurve** [comment]
We are going to address this separately as part of work on schemas.

**Comment by EgonBolton** [comment]
Is there a public place where it is being discussed what the possible solution will look like?
