### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by tsiege** [facebook/lexical#1728]
I know this is a big ask because it would require Native Bindings in Kotlin and Swift, but are there any plans to get React Native support for Lexical? It would be a game changer for many and to me would be a huge advantage in moving away from ProseMirror to Lexical. The use cases to me are obvious, being able to use one project across web and mobile operating systems

**Comment by amyworrall** [comment]
Which would be the most important considerations for you in a hypothetical React Native version of Lexical?

* Parity with web (supports the same node types, same features etc)
* Ability to extend Lexical via React Native, vs having to write new native code to extend Lexical's functionality
* Collaboration, serialized file format interchange, etc
* Multi-platform support in RN (i.e. would it only be useful to you if we had both iOS and Android, or would an iOS-alone RN version be of use?)

**Comment by TSiege** [comment]
Hey @amyworrall. Thanks for the quick reply. I think it's a combination of 1,2, and 4. I'm not sure how we could use Lexical outside of a web view on RN, which is problematic. Ideally there would be a Lexcial framework that is as low level as Lexical, but allows for native bindings to iOS and Android. I'd have to dig into this more but it seems likely that the core engine, such as `editorState`, of Lexical could be designed so that it's platform agnostic and exposes an API that swift or kotlin could use to render the WYSIWYG

**Comment by CanRau** [comment]
Yes please 🥺 React Native support would be tremendous 🥳

Ideally all 4 points 😅😇

**Comment by amyworrall** [comment]
As Dominic has hinted elsewhere, I’m leading a project to build native Lexical on iOS. I’m in the very early days of looking in to what a React Native wrapper around Lexical iOS would look like. The main sticking point is ensuring synchronous callbacks from JS to native, which requires bleeding edge RN features, but aside from that the issue will be the completely different layout engine for TextKit on iOS compared with DOM/CSS. So even if we enable building node subclasses in JS under RN, those node subclasses will have to use iOS semantics (providing string attributes rather than Dom nodes). That’s why I’m trying to find out what the most useful level of RN support would be, to ensure we focus on making that a good experience first. 

(I know I’ve not mentioned Android either. We have nothing to talk about there yet, alas.)
