### ISSUE TITLE
Q: React Toolbar plugin

### ISSUE THREAD

**Issue by mrodrigues95** [facebook/lexical#1760]
Are there any plans on adding something similar to https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/ToolbarPlugin.jsx to the current list of available plugins?

I have a use case for the above and was curious if this is something being added in the near future before I start to spend the time trying to create my own.

**Comment by zurfyx** [comment]
I don't think we want to publish it as it is now because it's very UI dependent so it may not fit well into the design patterns for most apps. It would have to be a more generic compoenent(s) where you can customize the buttons (add, remove, style). For now, I'd say, just copy-paste it and adjust it as it suits best for you.

@fantactuka - Mind sharing your thoughts since you've been exploring this space?

**Comment by fantactuka** [comment]
Right, it's unlikely we'll have "official" toolbar rendering (because each app will use their own), instead we can have have a set of utils to build it. Those tools will need to provide data regarding current selection/nodes:
- text format (bold, italic, ...)
- active block type (paragraph, heading, list, ...)
- active block style (left/right aligned, ...)
- whether it's a link

Or provide interface to plugins
- insert image
- run undo/redo

It can also expose methods to update that data (e.g. `toggleFormat('italic')`, `updateBlockType('heading1')`, ...). Since it's pure editor logic it will framework-agnostic, but @lexical/react package can include hook wrappers around it to simplify usage for react apps. It can be something like following:

```jsx
import { 
  useSelectedBlockType,
  useSelectedTextFormat,
} from '@lexical/react';

...

function BlockTypeDropdown() {
  const { 
    blockType,
    updateBlockType
  } = useSelectedBlockType();

  return <Select value={blockType} onChange={updateBlockType}> ... </Select>
}

function TextFormatButton({ type, label }) {
  const {
    isActive,
    toggleFormat,
  } = useSelectedTextFormat(type);

  return <Button label={label} isActive={isActive} onPress={toggleFormat} />
}

...

function Toolbar() {
  return (
    <BlockTypeDropdown />
    <TextFormatButton type="bold" label="Bold" />
    <TextFormatButton type="italic" label="Italic" />
    ...
  )
}
```

With this approach all editor specific logic will be encapsulated in those utils, and surfaces will only need to care about rendering part

Hope that helps!

**Comment by fantactuka** [comment]
Had another thought on it, it might be better to utilize commands similar as we do for history (UNDO, REDO, CAN_UNDO, CAM_REDO) and app will use those commands to update ui or change editor state

**Comment by ziedHamdi** [comment]
I noticed in the example [here](https://codesandbox.io/s/lexical-rich-text-example-5tncvy?file=/src/plugins/ToolbarPlugin.js:158-411) there was a lot of if-else handling eg.

```
    if ($isRangeSelection(selection)) {
      const node = getSelectedNode(selection);
      const parent = node.getParent();
      if ($isLinkNode(parent)) {
        setLinkUrl(parent.getURL());
      } else if ($isLinkNode(node)) {
        setLinkUrl(node.getURL());
      } else {
        setLinkUrl("");
      }
    }
```

I think, the api in React should more resemble to a state component where we would have a list of states listening hooks isBold, isList, etc... prefilled by the framework. Something like a library-provided list of hooks :
```
export default function ToolBar(props) {
  const {editor} = props
  const [isBold, setBold] = useState()
  //... other fields
  useEffect( ()=> registerBoldHook({isBold, setBold})
  
  return (
    <button onClick={setBold(!isBold)}>B</button>
  )}
```

I mean, it's good to have way to fall back to full control (like ranges, selection control, etc.), but the majority of users will just need a set of default use cases where things "just happen" and users adapt to how it was thought for them.
