### ISSUE TITLE
Bug: CodeBlock formatting deletes custom nodes like YoutubeNode, TweetNode etc in Lexical Playground.

### ISSUE THREAD

**Issue by sathishsridhar** [facebook/lexical#1779]
When we select a paragraph node and the paragraph contains a TweetNode or Poll or any kind of custom node and if we select all and try to format it with code block the custom nodes are deleted and its not rendered. 

I am attaching a video for reference. 

https://user-images.githubusercontent.com/21175404/163665718-b311a42a-8ca8-4a8f-b1f6-890a1c623eb6.mp4

I think the bug got introduced while fixing this #1644 issue. Only text data is retrieved from the selection and inserted back into the code block. 

Some of the fixes that I thought of : 
  Maybe the custom nodes can be parsed back to text and can be inserted into the code block and can be reparsed back to custom nodes again or maybe custom nodes can be ignored and only text can be formatted ( Not entirely sure how it would look for mentions and emojis ).

**Comment by thegreatercurve** [comment]
Sorry for delay in checking this out. 

I was able to verify the issue, but I don't necessarily feel like it's a bug. The fix for this particular issue would be to add a `getTextContent` to any `DecoratorNode` so when it's put into a CodeBlock, we can show some text instead.

I've verified this approach by adding the below into `YouTubeNode`: 

```js
  getTextContent(): string {
    return `https://www.youtube.com//watch?v=${this__id}`;
  }
```
