### ISSUE TITLE
Bug: creating lists fails

### ISSUE THREAD

**Issue by TrySound** [facebook/lexical#2129]
Lexical version: 0.2.7

## Steps To Reproduce

1. focus editor
2. write some text
3. click on numbered or bulleted list
4. see errors in console

Link to code example:

https://codesandbox.io/s/upbeat-forest-92ps3i?file=/src/App.tsx

## The current behavior

Error when I'm trying to create list by running command.
I tried to recreate the code from playground and got this error.
Maybe I'm missing something.

## The expected behavior

Working comand

**Comment by TrySound** [comment]
Also there is an issue with types I don't understand how to fix
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5635476/167690660-8a6a5d81-4087-4495-a1aa-e7a6bfa9c083.png">

**Comment by acywatson** [comment]
Yea, I think these types are wrong. The type declaration is written such that the expected argument is an instance of the class, rather than the class itself. Looks like there might be an unreleased fix here: 

https://github.com/facebook/lexical/pull/2116

As for the runtime failure, I think the issue is that you need to register the appropriate nodes in the LexicalComposer config. See the example in the playground here:

https://github.com/facebook/lexical/blob/f6986cff9fdcbb3ceb0b4faf26f252589b788133/packages/lexical-playground/src/App.tsx#L33

it's easy to miss that, the way they're spread. And it's also not really clear which nodes are used for which plugins. We are working on improving this.

**Comment by TrySound** [comment]
Great! Thanks! Works now. Looking forward for these changes. Glad to finally replace draft-js.
