### ISSUE TITLE
Feature: Intercept, validate, and potentially reject an update

### ISSUE THREAD

**Issue by tinleym** [facebook/lexical#2163]
My use case: I would like to impose a character limit on an editor, where any update that exceeds the limit is ignored. 

In the abstract, I think the functionality this use case requires is the ability to intercept, validate, and potentially reject an update.

Per a discussion I had with @acywatson on Discord, we considered the following options:

1. Commands. However, it will be tricky to intercept the right commands.
2. Node Transform. I don't think this will work when pasting multiline content.
3. Update Listener -- call parseEditorState w/ prevState and then call setEditorState w/ the result. Expensive, and might have unintended side effects (i.e. undo/redo).

Is there is a good (or better) way to do this w/ the library as stands?

Thank you!

**Comment by robwegbr** [comment]
Just to add to this one - since this is also very relevant for the use-case I've been struggling with. My use case is not to potentially reject an update but to modify it: e.g when a new character gets inserted, I'd like to insert as a custom text node.

It would be ideal if an update happens that you have some access to what the (intended) update is as well the editorState. 

Further thoughts that may be helpful: In DraftJS I solved this with the use of [handleBeforeInput](https://draftjs.org/docs/api-reference-editor/#handlebeforeinput).

From what I can tell, the INSERT_TEXT_COMMAND works similarly but it just doesn't fire on _every_ new character at the moment.

**Comment by trueadm** [comment]
I think what you want here is to use a node transform on RootNode (we can expose this). Specifically you want to be able to track the content size of the editor, and you probably want to use some form of cache to improve the runtime complexity. When your root transform runs you can traverse the tree, getting the content from all text nodes and line breaks, and caching the sub-tree text content for a branch in your cache. If you encounter the text content accumulated as being bigger, you can split the current text node and remove all subsequent text nodes and branches thereafter.

Given that transform operate in cycles, you can avoid doing this work O(n^2) by checking if a branch (an element node) is dirty and if not, using the stored value from the cache. So if you have to traverse through a large tree from the start, you can skip entire sub-trees of work making the operation much more efficient. This is actually how the reconciler for Lexical works!

**Comment by tinleym** [comment]
Clever! I can see myself using that pattern again and again.

Thank you for taking the time to respond... this isn't the first time you've taught me something (albeit the first time directly).
