### ISSUE TITLE
Feature: dedicated listener for user inputs

### ISSUE THREAD

**Issue by ZebraCat** [facebook/lexical#2240]
Would be great if we could have a listener that only fires when a user performs any edit, as opposed to the current listeners which fire also when we programatically add nodes.
an example - when a user presses a button, we want to render some text from the server in a certain style.
the requirement is that after a user performs any edit, we want to disable that style.

currently the way to do this is to listen to the beforeinput event on the root DOM element.
Would be great to have a dedicated library listener for this, I can think of many other examples that this would be useful for (distinguishing between a user input and a programatic mutation to the editor).

and example of what I'm trying to achieve:

![image](https://user-images.githubusercontent.com/11798411/169760360-9307175e-2e50-412b-8952-672b6830520a.png)
![image](https://user-images.githubusercontent.com/11798411/169760445-564ba1fb-856f-44ec-89b0-d76dd35f093c.png)

**Comment by trueadm** [comment]
From experience, it's not a great pattern to assume changes come from only user input. It's also very difficult to determine what is user input.

- Third party extensions, and spellcheckers generally don't trigger any events at all.
- You can't block or change content during composition (IME), and doing so causes a bad UX. This is particularly true for Android.
- Some user inputs aren't really what they seem to be. Sometimes a beforeinput event is ignored by Lexical, as we don't know what the terminated selection might be (text replacements).
- Generally speaking, we try and let the native browser do it's work rather than blocking it. Meaning listening during `beforeinput` isn't the always the same as what happens in `input`.
- Node transforms mean that sometimes an incoming input doesn't actually do anything, or gets transformed into something else. This is true for things like links, and nodes where input might go to an adjacent node.

A much better strategy is to use node transforms. Commands are not a good use-case for this sort of problem space. You can detect an edit on a text node, and then disable a style today with node transform.

**Comment by thegreatercurve** [comment]
Closing as Dominic's answer is pretty comprehensive about the limitations.
