### ISSUE TITLE
Bug: Inserting into the first line might cause scroll

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2495]
Lexical version: 0.3.5

## Steps To Reproduce

1. Place the caret into the first line
2. Use selection.insertNodes([...], false);

## The current behavior
In special cases scrollIntoViewIfNeeded() gets triggered. 

## The expected behavior
It should not scroll

https://www.youtube.com/watch?v=JXcazlsW-YM

This is the console.log in `scrollIntoViewIfNeeded()` which you can see in my video:
```
if (Math.floor(rect.top) < Math.floor(rootRect.top)) {
    element.scrollIntoView();
    console.log(element, rootElement, rect.top, rootRect.top);
}
```

Maybe here should be a check if rootElement is scrollable and only trigger this statement if it is.

**Comment by ttillberg** [comment]
I'm experiencing something similar because my elements are styled in such way the very bottom intersects the `rootRect` by 4px. I was able to fix it by moving around the styles but agree this behaviour should ultimately only be triggered if the editor is scrollable. and/or if it's intended.  This has been a "mystery bug" in our source for some time (it only occurs when hitting DEL key in a scrollable window) and it took a while to track it down to [that very line of code](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalUtils.ts#L1166) and I occurs to me other people will struggle with the same issue at some point.

Thoughts:

- Should `rootElement` be the first scrollable parent above instead of the `contentEditable` ? 
- Doesn't `LexicalAutoScrollPlugin.js` make this code redundant ? 
- I can't see how this code has any use at all since `root` is the `contentEditable` and is not meant to be scrollable (as per `Playground` example)

**Comment by rubenmoya** [comment]
The scroll in the playground is funky too.

Once there is scroll in the editor it starts to scroll down to the bottom on every new line. Then when you delete a line it moves up slowly.

Any workarounds to solve this?

![lexical](https://user-images.githubusercontent.com/905225/196193935-cf3441a0-525d-40c8-932d-6db2c53ca059.gif)

**Comment by thegreatercurve** [comment]
This should have been fixed with #3378. I can confirm that the last GIF is no longer replicable. 

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/7748470/203809080-7ff51360-4cc2-48bf-9b32-97b4275d6ffe.png">

**Comment by rubenmoya** [comment]
I can confirm it is fixed, thank you so much @thegreatercurve @trueadm! 👏

**Comment by jeremy** [comment]
🤖 This is still reproducible on `main` (and 0.47.0). `scrollIntoViewIfNeeded` still feeds `getBoundingClientRect()` of the collapsed selection straight to the scroller with no degenerate/out-of-bounds-rect guard.

A concrete RTL manifestation of the same code path: on **Safari**, a collapsed caret in RTL text (Arabic/Hebrew) returns a degenerate, out-of-bounds rect (negative `top`) — worst at whitespace/line boundaries, i.e. after space/backspace. Safari also reports such a collapsed caret as `selection.type === 'Range'`, which makes `$updateDOMSelection` skip its early-return (the *"Badly interpreted range selection when collapsed - #1482"* case) and fall through into this scroll block. The window then scrolls **up** on every keystroke and the editor is pushed off-screen. Chrome/Firefox are unaffected.

I opened #8848 implementing essentially the guard proposed in this thread — skip the scroll when the selection rect lies entirely above `rootElement`, since a caret that lives inside the editor cannot — with a unit test. It's framed as browser-agnostic geometry hardening rather than an RTL/Safari special-case.
