### ISSUE TITLE
Feature: Methods that return ReactNodes from editor, such as $generateHtmlFromNodes

### ISSUE THREAD

**Issue by akichim21** [facebook/lexical#2516]
I use Next.js.
I would like to use next/image, and generate ReactNode at SSR if possible.
If the above can be done,
  - it will be possible to do other things such as client rendering when youtube iframes are slow.
  - It does not store html in the database and is resistant to html changes.
  - I will be able to use swiper/react and other libraries that depend on react.

Are there any plans to provide a method that return ReactNodes from editor?

**Comment by trueadm** [comment]
Short answer is no. Only DecoratorNodes can return React elements and this is for a very important reason - Lexical doesn’t have knowledge of what happens inside a decorator unless told so. So things like selection do not work natively. React has its own system that doesn’t work too well with content editables - due to how React expects to own the DOM, when in reality that’s never true in a contenteditable. So we mark decorator nodes as not editable to avoid bugs.

Slate and Draft allow React component content to be editable, but this is a huge source of unfixable bugs (trust me, I used to work on the React team).

**Comment by akichim21** [comment]
Thanks for the reply. I understand.

**Comment by akichim21** [comment]
I understand that contenteditable is difficult.
However, since contenteditable is not used in the part of displaying articles (html), what about the pattern of generating ReactNode from JSON (data stored in DB)?
Maybe it would be double management(HTML & ReactDOM) and difficult to maintain.

**Comment by trueadm** [comment]
Generating Lexical nodes that will be used for a text editor will absence the same issues whether the backing format is HTML or JSON. Did you mean for read only mode?

**Comment by akichim21** [comment]
> Did you mean for read only mode?

Yes. 
I don't want to create any instances of LexicalEditor or RangeSelection (NodeSelection | GridSelection) when using ReactNode(You can create a LexicalEditor inside a generate method if you want.)
because I only want to display it to the user and do not want to use the editing functionality.

When optimizing the display, there should be a need to parse JSON and display it in various frameworks (React, Vue, ios Swift, android Java, React Native etc), and we believe that React (ReactNode) is worth supporting among them.

**Comment by akichim21** [comment]
If it is not supported, we are considering creating our own method that returns a ReactNode in the form of the following issue.
https://github.com/facebook/lexical/issues/2020#issuecomment-1129083803

**Comment by trueadm** [comment]
That's the best approach for doing this IMO.

**Comment by akichim21** [comment]
OK.
Thanks for the reply.
