### ISSUE TITLE
Bug: `@lexical/markdown` `text-format` combination

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2632]
When hydrating a lexical editor with the following markdown `**Bold *Italic***` calling `$convertFromMarkdownString` should properly format this as bold & and bold italic text. However, for some reason, it doesn't, and the rendered result is **`Bold *Italic*`**

This seems to work when switching between editor content and markdown in the playground, but it does **not** work when initializing the playground with this content.

Lexical version: 3.8

## Steps To Reproduce

1. Have a lexical instance with `initialEditorState` that invokes `$convertFromMarkdownString('**Bold *Italic***')`
2. See the content be rendered in editor as **`Bold *Italic*`** rather than the expected **`Bold` *`Italic`***

Link to code example:

https://codesandbox.io/s/many-lexical-autofocus-forked-efq8sq?file=/src/App.js

## The current behavior
Content is Bold and asterisks are rendered in editor

## The expected behavior
Content should be Bold and Italic text should be italicized

--

Happy to share any more information if it's useful

**Comment by hanford** [comment]
Narrowed the issue down to a bug in [this function](https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/v2/MarkdownImport.ts#L201), where when splitText is called, it can break up markdown format syntax so it's not formatted...

i.e. the following markdown syntax will never be imported correctly:

```
*Foo **Bar***
**Foo *Bar***
_Foo __bar___
__Foo _bar___
``` 

When `findOutermostMatch` is called on the above pieces of markdown, it wrongly identifies the outer most pieces of markdown, causing the other contents to then be "split" and subsequent formatting is never formatted correctly

In the first case, ```*Foo **Bar***```, `findOutermostMatch` wrongly returns `**Bar**`, then `splitText` is called, and the `leadingNode` and `remainingNode` are `*Foo` and `*` respectively, causing lexical to then render

<img width="645" alt="image" src="https://user-images.githubusercontent.com/2148168/181378254-51dfc953-426d-4549-b999-9eea1a53826c.png">

**Comment by fantactuka** [comment]
@hanford Thanks for digging into it! Was suspecting findOutermostMatch is not working correctly but didn't get a chance to play with regExp. The question is if it's even possible with regExp only. Especially for cases like above when `***` is a closing tag for separate `*` and `**`. So the logic would be if we have `*` and `**` opened, then the next `***` is their combined closing tag, and we don't need to look for any `*` or `**` further. 

Maybe getting all tags matches (with its corresponding matching indices) and then walking through that list, so that we have info of currently started tags which can be used to distinguish between `***` being a single tag or two combined closing tags

**Comment by hanford** [comment]
refs https://github.com/facebook/lexical/issues/2303

**Comment by focux** [comment]
I'm having this same issue when using bold and italics, however, in your case bold was still working but not italics, and now, none of them is working, seems like something broke in the latest version, here is a reproduction:

https://codesandbox.io/s/lexical-bold-and-italics-not-working-99cg7q

**Comment by 777PolarFox777** [comment]
Looks like there's also an issue when you apply bold/italic on a line that has a a space character after an emoji in the end:
<img width="909" alt="image" src="https://github.com/facebook/lexical/assets/19393384/e900b205-5ff8-4194-9d1f-ad8e8a1c80fa">


<img width="909" alt="image" src="https://github.com/facebook/lexical/assets/19393384/5aa4e1d9-2d9f-4c26-b3a3-176e674d633c">

Not sure if it's a new issue or related

**Comment by aklatzke-kraftful** [comment]
For anyone running into this issue, here's a workaround you may be able to use. 

For me, this was manifesting as the following:

- Create some bold/italic text in an editor as part of a paragraph
- Export to markdown, using the provided plugin utilities ($convertToMarkdownString)
- Reload the editor
- The text is now gone because it was parsed incorrectly using the provided utility ($convertFromMarkdownString)
- Subsequent auto-save would wipe the text from the document

To workaround this, I used the alternate markdown syntax for bold/italics (`___` instead of `***`) and implemented it in a custom transformer.

```typescript
import { Transformer } from "@lexical/markdown";
import { $createTextNode, $isTextNode, LexicalNode, TextNode } from "lexical";

function $createBoldItalicNode(text?: string) {
  const node = $createTextNode(text);
  node.toggleFormat("bold");
  node.toggleFormat("italic");
  return node;
}

function $isMarkdownBoldItalicNode(node: LexicalNode): boolean {
  return $isTextNode(node) && node.hasFormat("bold") && node.hasFormat("italic");
}

export const BOLD_ITALIC_TRANSFORMER: Transformer = {
  export: (node) => {
    if (!$isMarkdownBoldItalicNode(node)) {
      return null;
    }

    return `___${node.getTextContent()}___`;
  },
  dependencies: [TextNode],
  regExp: /___(.+?)___/,
  importRegExp: /___(.+?)___/,
  trigger: "___",
  replace: (parentNode, match) => {
    const [, text] = match;
    parentNode.replace($createBoldItalicNode(text));
  },
  type: "text-match",
};
```

Then registered this as the first transformer:

```typescript
export const TRANSFORMER_COLLECTION = [
  BOLD_ITALIC_TRANSFORMER,
  ...TRANSFORMERS,
];
```

This fixed the editor issue, you just need to ensure everything else in your pipeline supports the `___` syntax for the formatting.

**Comment by etrepum** [comment]
Should be fixed by #5758

**Comment by AlexandrDubovchenko** [comment]
Still have same issue.

Steps to reproduce:

Provide $convertFromMarkdownString with **Bold*Italic***

Result is:  **Bold \*Italic\***

Lexical version: 0.38.2

@etrepum @yhw5 Please check

**Comment by Yith1** [comment]
> Still have same issue.
> 
> Steps to reproduce:
> 
> Provide $convertFromMarkdownString with **Bold_Italic_**
> 
> Result is: **Bold *Italic***
> 
> Lexical version: 0.38.2
> 
> [@etrepum](https://github.com/etrepum) [@yhw5](https://github.com/yhw5) Please check

Also still having this issue using Lexical 0.39.0.

I asked Claude to do some analysis of the problem. Apologies if it has hallucinated. Here is it's output:

## Test Cases 
```typescript
import { $convertFromMarkdownString } from "@lexical/markdown";
import { $getRoot } from "lexical";

// ✅ WORKS: Simple cases
$convertFromMarkdownString("*italic*", TRANSFORMERS);
// Result: <em>italic</em> ✓

$convertFromMarkdownString("**bold**", TRANSFORMERS);
// Result: <strong>bold</strong> ✓

$convertFromMarkdownString("***bold and italic***", TRANSFORMERS);
// Result: <em><strong>bold and italic</strong></em> ✓

// ✅ WORKS: Properly balanced nesting
$convertFromMarkdownString("**bold with *italic* inside**", TRANSFORMERS);
// Result: <strong>bold with <em>italic</em> inside</strong> ✓

$convertFromMarkdownString("*italic with **bold** inside*", TRANSFORMERS);
// Result: <em>italic with <strong>bold</strong> inside</em> ✓

// ❌ FAILS: Overlapping delimiters (opener before opener, closer after closer)
$convertFromMarkdownString("ggggg*jhhhh**dsjdhjdj***", TRANSFORMERS);
// Expected: ggggg<em>jhhhh<strong>dsjdhjdj</strong></em>
// Actual: ggggg*jhhhh<strong>dsjdhjdj</strong>* ✗
```
## Root Cause Analysis

After investigating the `@lexical/markdown` source code, the issue appears to be in the `findOutermostMatch` function in `LexicalMarkdown.dev.js` (lines 308-340).

### The Algorithm Flaw

The current algorithm:
1. Finds all opening tags using `openTagsRegExp` in a **left-to-right scan**
2. For each opening tag (in order of appearance), tries to match its full pattern
3. Returns the **first successful match**

This is a greedy left-to-right approach that doesn't respect CommonMark's emphasis delimiter matching rules.

### Why It Fails on `*jhhhh**dsjdhjdj***`

1. Scanner finds `*` at position 5, `**` at position 11
2. Tries to match `*...*` for position 5 → **NO MATCH** (finds `*jhhhh**` which has `**` at the end)
3. Tries to match `**...**` for position 11 → **MATCH!** (`**dsjdhjdj**`)
4. Applies bold formatting, leaving `*jhhhh` and `*` as literal characters

### CommonMark's Algorithm

Per the CommonMark spec, emphasis delimiter matching should:
1. Identify delimiter runs and apply **flanking rules**
2. Process emphasis from **innermost to outermost**
3. Match delimiters based on **precedence** (*** before ** before *)
4. Handle overlapping by respecting the **delimiter stack**

The CommonMark algorithm is significantly more complex than Lexical's current implementation. See [CommonMark spec section 6.2](https://spec.commonmark.org/0.31.2/#emphasis-and-strong-emphasis) for the full algorithm.

## Reproduction

### Minimal Test Case

```typescript
import { createHeadlessEditor } from '@lexical/headless';
import { $convertFromMarkdownString, TRANSFORMERS } from '@lexical/markdown';
import { $getRoot } from 'lexical';

const editor = createHeadlessEditor({
  nodes: [],
  onError: (error) => console.error(error),
});

editor.update(() => {
  $convertFromMarkdownString('ggggg*jhhhh**dsjdhjdj***', TRANSFORMERS);
  const root = $getRoot();
  console.log(root.getTextContent()); // Shows: ggggg*jhhhhdsjdhjdj*
});
```

### Automated Test

```typescript
describe('@lexical/markdown emphasis parsing', () => {
  test('should handle overlapping emphasis delimiters per CommonMark spec', () => {
    const editor = createHeadlessEditor({
      nodes: [],
      onError: (error) => console.error(error),
    });

    editor.update(() => {
      $convertFromMarkdownString('ggggg*jhhhh**dsjdhjdj***', TRANSFORMERS);
      const root = $getRoot();
      const html = root.getFirstChild()?.exportDOM().element?.innerHTML;

      // Should have nested em and strong tags
      expect(html).toContain('<em>');
      expect(html).toContain('<strong>');
      expect(html).toMatch(/ggggg<em>jhhhh<strong>dsjdhjdj<\/strong><\/em>/);

      // Should NOT have literal asterisks
      expect(html).not.toContain('*');
    });
  });
});
```

**Comment by etrepum** [comment]
If you’re experiencing a problem you should open a new issue rather than comment on one that’s been closed

**Comment by Yith1** [comment]
> If you’re experiencing a problem you should open a new issue rather than comment on one that’s been closed

Done: https://github.com/facebook/lexical/issues/8073
