### ISSUE TITLE
Feature: Get a reference to the node that's about to be deleted

### ISSUE THREAD

**Issue by xanderjakeq** [facebook/lexical#2685]
I am trying to do something like the mention plugin but only mention an item once. In this state, Aayla should not be on the list of options. When the mention node is deleted, Aayla should return to the list.

![image](https://user-images.githubusercontent.com/13279523/180442468-26516b21-f570-4ec0-81f2-5f1787caa3b8.png)

The `registerMutationListener` tells when a node is deleted, but not which one.  `$getNodeByKey` or `editor.getElementByKey` will 
 return `null` when called after a `destroyed` mutation.

The mention node I'm trying to make has an X button. I can be deleted by clicking the X button or pressing backspace. When deleted by the button, I can get the reference to the node, with the backspace, my workaround for this is to listen for `KEY_BACKSPACE_COMMAND` then `$getSelection().getNodes()`.

It would be nice to be able to do that in one place.

**Comment by thegreatercurve** [comment]
If I understand this correctly, you want to get access to a deleted node after it has been `destroyed`? 

I'm not sure if the best place for that is necessarily the `registerMutationListener` callback, especially as we do include the `key` for the  destroyed node as the key of the map in the first argument in for the callback:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/7748470/180753983-ae4e1c80-499e-409b-952b-da6ee2198ca4.png">

You workaround seems like a fien alternative. Otherwise, you can potentially store the `previousActiveNode` in a ref. 

A better solution for your use case might be just to keep an array of `activeMentions`, update it any time a mention gets added or removed, and then just filter it from the dropdown.

**Comment by acywatson** [comment]
> A better solution for your use case might be just to keep an array of activeMentions

This is actually a good idea, but you probably want to use a Map instead of an array, as you'll need to match the key up to the deleted mention, since the key is all you get on delete.

**Comment by moughxyz** [comment]
Here's a plugin that works for me:

```typescript
import { useEffect, useRef } from 'react'
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'
import { $getNodeByKey, Klass, LexicalNode } from 'lexical'

type NodeKey = string
type ItemUuid = string

type ObserverProps = {
  nodeType: Klass<LexicalNode>
  onRemove: (itemUuid: string) => void
}
export function NodeObserverPlugin({ nodeType, onRemove }: ObserverProps) {
  const [editor] = useLexicalComposerContext()
  const map = useRef<Map<NodeKey, ItemUuid>>(new Map())

  useEffect(() => {
    const removeMutationListener = editor.registerMutationListener(nodeType, (mutatedNodes) => {
      editor.getEditorState().read(() => {
        for (const [nodeKey, mutation] of mutatedNodes) {
          if (mutation === 'updated' || mutation === 'created') {
            const node = $getNodeByKey(nodeKey)

            if (node) {
              const uuid = node.getId()
              map.current.set(nodeKey, uuid)
            }
          } else if (mutation === 'destroyed') {
            const uuid = map.current.get(nodeKey)
            if (uuid) {
              onRemove(uuid)
            }
          }
        }
      })
    })

    return () => {
      removeMutationListener()
    }
  })

  return null
}

```
