### ISSUE TITLE
Table cells as their own editor

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2792]
Tables are hard to get right. Each cell can potentially have as much complex text as the editor itself and we have to handle every edge independently. For example, you can add a header in a cell and some text below.

Adding an H2 is currently broken, it breaks the whole cell. This is mostly because we considered headings to be top-level nodes and this no longer is true when they're inside a cell.

Arguably there's two ways of fixing this problem:
1. Headers to gracefully support living inside table cells
2. Table cells being their own editor

The reason why I'm inclined towards 2 is because there will always be infinite cases that we will handle to handle and each developer will have to handle with their own nodes, whereas an editor would automatically adhere to these rules without extra code.

## What is more

**Customization**

A cell editor gives you flexibility to customize the editor in a very natural way. We already defined a set of plugins that can be plugged in easily in an editor, we can reuse the same mechanism for cells.

A feature request that seems pretty decent is to have plain text inside a cell instead of rich text. Currently that requires intercepting rich text, including paste converters, so the level of effort is hard compared to trivial with its own editor.

**As bug free as an editor itself**

No more edge cases. Just another editor.

## Trade-offs

We lose control of the content in the cell, or at least, it's harder to control. Besides that, probably efficiency. But practically speaking you can't do more than you can't do now. For example, it's impossible do RangeSelection between text living in two different cells.

## Approach

A DecoratorNode or new editor instances attached to nodes.

The first is more natural and would work out of the box with our currently infra. The only downside is that it would only work for React. However, that may be a reasonable trade-off.

**Comment by fantactuka** [comment]
> The first is more natural and would work out of the box with our currently infra. The only downside is that it would only work for React. However, that may be a reasonable trade-off.

Curious why it would be limited to react?

**Comment by echarles** [comment]
> Table cells being their own editor

That would be my first preference, without thinking too much. It sounds super cool to be able to have like Excel/Google Sheets the ability to format the table content.

> Besides that, probably efficiency

That was my second tough. I have just tried now to display many plain and rich editor on on page with 

```ts
      <h1>Lexical Many Editors</h1>
      {
        [...Array(1000).keys()].map(i => {
          return <Editor />
        })
      }     
```

With many plains, I can reasonability go to 1000 editors and it remains fast (a few seconds to display, scrolling is OK).

With many rich editor, 100 is OK, but 1000 begins to be slow to display (15 seconds) and then the display just disappears.

**Comment by EgonBolton** [comment]
I propose a different architecture optimized for tables. As you can see, the model I describe below deviates a bit from the 1 LexicalNode = 1 DOM node principle, and therefore Lexical's native rendering would not work. The solution would be for Table to be a DecoratorNode whose content is made up of [Lexical Headless Editor](https://lexical.dev/docs/api/lexical-headless), with new and different rendering logic.

The classes that make up a table and its basic properties would be as follows:

```jsx
class Table {
	rows: Map<rowKey, Row>;
	columns: Map<columnKey, Column>;
}

class Row {
	key: rowKey;
	prev: rowKey;
	next: rowKey;
	cells: Map<columnKey, Cell>;
}

class Column {
	key: columnKey;
	prev: columnKey;
	next: columnKey;
        pos: number; // this is to skip empty cells when rendering.
	width: number;
}

class Cell {
        column: columnKey:
	content: LexicalEditor;
}
```

Note: although the properties rows, columns and cells I defined there as "maps", they should be a Lexical editor. Remember that I am proposing headless editors so rendering would not be a problem. The reason for using a Lexical editor would be to benefit from double buffering, transformations, listeners, and RTC.

# Advantages

Some advantages of the new model over the current one, along with the implementation of a new rendering logic:

1. Only non-empty cells are stored in memory.
2. If C is the number of columns and R\*C is the number of cells, Lexical's current model requires O(R\*C) to insert, delete, or sort columns; while the model I propose requires only O(C). Note that if we remove the `pos` column property, it could be O(1), but thanks to that property we achieve the following...:
3. We can render each row by iterating only over its cells (non-empty cells) and without using the map's hash function (since iteration order doesn't matter).
4. [getCordsFromCellNode](https://github.com/facebook/lexical/blob/30ad13bcc637dfc61cb15aaa45e3d13bcf7d9602/packages/lexical-table/src/LexicalTableNode.ts#L124) will be automatic instead of O(R*C), and accessing the four adjacent cells will be O(1).
5. It would allow ordering the rows by columns.
6. It would allow filtering rows with different criteria.
7. It allows each cell to be a different editor but at the same time gives more control over when the cells will be content-editable. For accessibility reasons, the content-editable could be changed only on the focused cell, or even on an overlay div.

# Future

1. In the classes I have limited the properties to those related to document tables, and that do not apply to more specific cases or spreadsheets, such as formula, hide, or wrap.
2. Considering that (a) many spreadsheets like Gsheets allow adding thousands of new rows at once, (b) Excel shows unlimited empty rows on demand when scrolling, and (c) some spreadsheets like Gnumeric group adjacent cells with the same content in the model; then It has occurred to me to add the `skip` property to the rows, which indicates the number of empty rows that proceed to the current one. However, I don't think it would add a significant gain to the complexity it would add.
3. It remains to decide how the cell grouping could be modeled.
4. Consider properties that can be set for an entire column or row, as well as for specific cells (for example, background-color). In that case, that property could be added to the 3 classes (column, row, and cell) and timestamp together with the property, giving priority to the last to be set.

# Review of Main Spreadsheets

Undoubtedly the most popular open source spreadsheets are a family of programs derived from StarOffice. Some of these programs are already discontinued. The most used today is LibreOffice.

![image](https://user-images.githubusercontent.com/43938777/184569075-09e4d872-274a-4d5d-9b88-0815d08d375a.png)
Source: [Wikipedia](https://en.wikipedia.org/wiki/Collabora_Online).

The best explanation I've found of this spreadsheet architecture is [this OpenOffice wiki entry](https://wiki.openoffice.org/wiki/Calc/Implementation/Data_Model_for_sheet_and_cell).

In short, they use a fixed array for the columns, and a dynamic array for the rows, whose space has been expanding over time. LibreOffice since version 7.4 uses an array of 16,384 spaces for the columns and a maximum of 1,048,576 for the rows, thus matching Microsoft Excel.

Cells are arranged within columns (I'm quite surprised they don't reside in rows), and only non-empty cells are stored in memory.

There are other open-source spreadsheets that are not derived from StarOffice. [This Wikipedia table](https://en.wikipedia.org/wiki/List_of_spreadsheet_software#Specifications) compares the limit of rows and columns that they allow.

I haven't spent as much time understanding the architecture of some like Calligra or Gnumeric; but seeing that the limit of rows and columns are powers of 2, I suppose that they are also built on arrays of rows and columns.

According to the table, the only ones that don't seem to impose a limit are Pyspread, and Resolver One (the latter's creators have actually abandoned that project and started a new spreadsheet called [Dirigible-Spreadsheet](https://github.com/pythonanywhere/blimp-spreadsheet)).
From what I've seen and understood of these two programs, I THINK they don't define any class or object for rows or columns as such. They only have "cells", which consist of a dictionary with two keys: row and column.

Finally, I haven't found much information about the two most used closed source programs, Excel and GSheets. Although in the [GSheets API](https://developers.google.com/sheets/api/guides/concepts) it says that the cells "don't have a unique ID value. Instead, row and column coordinates identify the cells." This makes me think that they don't group cells within rows (as I propose) or within columns (as LibreOffice does).

# Relevant Reading

https://en.wikipedia.org/wiki/List_of_spreadsheet_software

https://en.wikipedia.org/wiki/Comparison_of_spreadsheet_software

https://en.wikipedia.org/wiki/Spreadsheet)(https://en.wikipedia.org/wiki/Spreadsheet

https://medium.com/google-cloud/system-designing-google-sheet-bdf12321b99c

https://wiki.openoffice.org/wiki/Calc/Implementation/Data_Model_for_sheet_and_cell

https://wiki.openoffice.org/wiki/Sc

https://niocs.github.io/LOBook/calcarch/overview.html

https://niocs.github.io/LOBook/misc/16kcols.html

https://docs.libreoffice.org/sc/html/annotated.html

https://stackoverflow.com/questions/2025316/why-do-most-spreadsheets-contain-a-hard-coded-limit-on-the-number-of-rows-and-co

https://stackoverflow.com/questions/238328/database-best-way-to-model-a-spreadsheet

**Comment by acywatson** [comment]
> 

A couple of clarifying questions here:

You're proposing that each cell is a headless editor, right? What's the benefit of making them headless? I'm not following why you'd need to change the rendering logic or how you'd change it to accommodate the proposed design.

**Comment by EgonBolton** [comment]
Oh yeah, I was wrong on that part. Cell should be a normal lexical editor. What requires a different architecture and thus different rendering logic would be the rows and columns within the table.

I have clarified those parts in the previous message.
