### ISSUE TITLE
Bug: Multiline Quotes are difficult

### ISSUE THREAD

**Issue by gdelmas** [facebook/lexical#2889]
https://user-images.githubusercontent.com/2949816/186534695-dd903009-bbea-449e-bd41-de7040219e31.mov

- pressing enter in a quote-block, returns to normal paragraph
  - unfortunately also when pressing enter in the middle of the text of a quote
- it appears impossible to have a multi-line (returns) in a quote. the quote line on the left gets disconnected.

It would be nice to be able to create quotes with multiple lines. If we want quotes to close on enter press, we should at least wait for two enters. We should also connect quote blocks that are siblings into one.

cc @zurfyx

**Comment by trueadm** [comment]
Can’t you use shift+enter?

**Comment by gdelmas** [comment]
Yes, that works. I would not have discovered it. 

I wonder why bulleted, numbered and check lists and code blocks allow to simply press enter (without shift). What is different about quotes, that they need to behave differently?

**Comment by trueadm** [comment]
Shift+Enter is quite a well known key command to add soft line breaks. Lists are different because you're actually inside a list block, instead of the root. So the context of the list is to add a new item to that list. This is how other text editors work too.

Code blocks are handled with a special case here to emulate code editing, but in most editors they also work like how quote/heading nodes work too.

**Comment by thegreatercurve** [comment]
Closing this task as I feel like this is fairly standard behaviour, replicable on Slack and Discord.
