### ISSUE TITLE
Bug: Command Listener doesn't allow event to propagate to low priority listener

### ISSUE THREAD

**Issue by 1kvsn** [facebook/lexical#2978]
The KEY_ENTER_COMMAND command listener with COMMAND_PRIORITY_LOW is not allowing the event to propagate and the ENTER listener with lower priority like COMMAND_PRIORITY_EDITOR doesn't get fired.

Raising this issue as per the Discord conversation with @acywatson here: https://discord.com/channels/953974421008293909/954448555899236422/1017670618491138048

Lexical version: 0.4.0

## Steps To Reproduce

1. Add any plugin which listens for KEY_ENTER_COMMAND with COMMAND_PRIORITY_LOW. For example, LexicalTypeaheadMenuPlugin has KEY_ENTER_COMMAND listener with COMMAND_PRIORITY_LOW
2. Add one more KEY_ENTER_COMMAND listener anywhere with COMMAND_PRIORITY_EDITOR
3. When you press ENTER, the listener with COMMAND_PRIORITY_LOW fires and the event doesn't propagate to other ENTER listener with COMMAND_PRIORITY_EDITOR priority even though the first listener returned "false". 

Link to code example ( codesandbox steps provided below the link ):
https://codesandbox.io/s/hardcore-forest-tbnyng

1. Open the codesandbox
2. Open ToolbarPlugin, line # 520.
3. You'll see two KEY_ENTER_COMMAND listeners are added with different priorities.
4. In the UI, open Console, focus on the Editor and press ENTER key to see console output.
5. There is one more KEY_ENTER_COMMAND listener added in TreeViewPlugin in same sandbox.

## The current behavior
When the ENTER listener with COMMAND_PRIORITY_LOW is returning false, the event doesn't propagate to ENTER listener with COMMAND_PRIORITY_EDITOR

## The expected behavior
When a command listener is returning false, the event should propagate to same command listeners with lower priority until one returns true or there are no more handlers to invoke.

**Comment by trueadm** [comment]
Have you checked to see if another command listener is returning true for the same command somewhere?

**Comment by acywatson** [comment]
> Have you checked to see if another command listener is returning true for the same command somewhere? If you remove all plugins, including the core ones, you’ll see that it does correctly bubble.

If this is the case, it's still a problem, since they won't have control over the implementation of those core plugins. 

I think we need to consider allowing users to specify the behavior of the onSelect event in the TypeaheadMenuPlugin, and perhaps adopt a similar model for other plugins. As plugins proliferate, we need to provide more flexibility to users to control how they interact with other plugins.

**Comment by trueadm** [comment]
Shouldn’t custom plugins be using a priority higher than editor anyway? That priority was designed for the core editor plugins and is the lowest so any other priority can come in before. Maybe I’m missing something here though?

**Comment by acywatson** [comment]
> Shouldn’t custom plugins be using a priority higher than editor anyway? That priority was designed for the core editor plugins and is the lowest so any other priority can come in before. Maybe I’m missing something here though?

No you're right - I think I was mentally inverting the priorities.

You should have the typeahead plugin enter handler executing, then the submit handler (userland) then the core. I think the problem must be that the typeahead plugin is incorrectly stopping propagation to the submit plugin (assuming they're the same priority and submit is registered second). Otherwise, not sure why it wouldn't be working.

**Comment by trueadm** [comment]
@thegreatercurve Please could you re-test this one as it might be the source of a larger bug if it is.
