### ISSUE TITLE
Bug: selection can move, but not extend, out of inline-flex nodes

### ISSUE THREAD

**Issue by shirakaba** [facebook/lexical#2991]
Lexical version: `0.4.1`

## Steps To Reproduce

*Note that the setup steps 1-3 have been completed in advance in the Codesandbox linked below.*

1. Create a class named `InlineFlexNode` that extends `ElementNode`. Its `createDOM()` method should return a HTMLSpanElement with `display: inline-flex`.
2. Place the InlineFlexNode after a TextNode (with the text "Text outside, and:").
3. Insert a TextNode (with the text "Text inside") into the InlineFlexNode.
4. Click on the start of the "Text inside" text node (offset 0).
5. Hold down `Shift`.
6. Press `ArrowLeft`.

Link to code example:

https://codesandbox.io/s/element-selection-stuck-repro-forked-xe1ic7?file=/src/App.js

## The current behavior

The selection extends left in Firefox, but not in Chrome, nor in Safari (where it is unable to extend leftward from its starting position).

Of note, moving left (rather than extending left) works fine on all browsers.

### Chrome and Safari (buggy)

The I-bar gets stuck on its original position:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/14055146/189563554-078b8d2c-6c52-43fc-99aa-71b4dbcba7e8.png">

### Firefox (correct)

The I-bar disappears, indicating that it has moved leftward from the text node to the element.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/14055146/189563753-213cf0d7-29f2-4047-ac30-484a317944e6.png">

Extending the selection box further to the left shows a selection box forming.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/14055146/189564099-5fec9e63-b6e9-42bc-824a-ff771fab7684.png">

## The expected behavior

The selection should extend leftward from its current position, as it does in Firefox.

## Severity

This means that it is impossible to select across an inline-flex node character-by-character on Chrome and Safari. Inline-flex is a useful display mechanism for laying out content.

## Cause

I believe it is something to do with how `internalResolveSelectionPoint()` handles selections resting on element nodes (rather than text nodes):

https://github.com/facebook/lexical/blob/1580cbc2687605d307df6d4af9d56ba325fbb5e0/packages/lexical/src/LexicalSelection.ts#L1974

**Comment by trueadm** [comment]
If you have a standard contenteditable, with no JS library and use the CSS properties does this work properly for you?

**Comment by shirakaba** [comment]
@trueadm Yes, it works properly on all browsers when using an equivalent contenteditable - I've included it in the Codepen for comparison.

**Comment by trueadm** [comment]
Are you marking your `inline-flex` custom element as inline? Using the `isInline() { return true }` method?

**Comment by trueadm** [comment]
I'll take a deeper look into this later. Does the issue go away if you make it non flex inline with CSS? I'm trying to work out what part of the logic could be getting confused here. It might be `selection.modify` which under the hood uses `domSelection.modify(alter, direction, granularity);`.

**Comment by birtles** [comment]
I believe when we debugged it, the issue was that given this content Chrome (and Safari I suppose) would end up moving the selection focus to an ancestor element of the text node it previously pointed to (it would also move the anchor to a parent element although that might not be related). When lexical came to adopt the DOM selection, it would normalize it, moving the selection endpoints to descendant child text nodes -- i.e. back where the selection started.

In Firefox, however, performing the same action on the same content would cause the selection focus to move to the previous text node.

**Comment by trueadm** [comment]
I think the bug is these lines:

https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.ts#L234-L236

Specifically, the normalization logic isn't doing anything wrong here. If we have a chid within an element at an offset (in this case we do) then we normalize selection to be that of the child rather than the parent. However, we only update the DOM with Lexical's selection if the selection was marked as dirty. In the above lines, it seems we *always* mark selection is dirty when Lexical's selection is collapsed but the DOM selection is a range – which doesn't seem right. If you remove those lines then the issue should go away. I wonder if there's a better fix for the original issue at hand (as stated in the comment).

**Comment by shirakaba** [comment]
@trueadm Thank you for the quick response, and especially for coming up with a potential solution!

I made an extra Codepen to check for regressions when selecting across two sibling `inline-flex` elements (which appears to work on all browsers in Lexical 0.4.1, so we'd hope that this change doesn't undo it):

<img width="632" alt="image" src="https://user-images.githubusercontent.com/14055146/189788086-5b5335b2-a1d6-4bbf-9a49-180c12bf0841.png">

https://codesandbox.io/s/element-selection-stuck-repro-forked-3w7d34?file=/src/App.js

It does solve this current issue, though introduces a regression in another LexicalElement we have (which has `user-select: none`), often side-by-side with the `inline-flex` LexicalElement - the selection now can't extend past the `user-select: none` LexicalElement. I'll need to prepare another minimum working example to compare to, as it's hard to explain otherwise.

I'll catch up with @birtles on Thursday to discuss, so provisionally intend to get back to this ticket around then.

**Comment by shirakaba** [comment]
Regarding this bit in the previous comment:

> However, the patch sadly does introduce a regression in another LexicalElement we have (which has `user-select: none`), often side-by-side with the `inline-flex` LexicalElement, which will take some explaining - the selection now can't extend past the `user-select: none` LexicalElement. I'll need to prepare another minimum working example to demonstrate.

I've investigated further and have concluded that actually something else was at fault, and the bug I was seeing seems to occur regardless of whether your Lexical patch is applied. I also couldn't produce a minimum working example in Codepen, so I've concluded that it's a problem I've introduced in userland that should be fixable.

This PR fixes the issue in question without introducing any regressions in any of our test cases. Thank you!
