### ISSUE TITLE
Question: Dynamic Content in Nodes

### ISSUE THREAD

**Issue by seanchambo** [facebook/lexical#3012]
I want to create a mention node (inline) that only stores the users id. The users information would then be fetched when the node is mounted using a rest api or and update the appearance of the node once the information is available. Is there a good way to do this at the moment?

Is it possible to do this with a DecoratorNode? Are DecoratorNode able to be used inline?

**Comment by zurfyx** [comment]
You can use a DecoratorNode but I would strongly recommend against it, especially for a TextNode. You will lose some of the a11y benefits and performance that otherwise you would get with a raw TextNode.

Instead, you can print a normal TextNode and manipulate it externally. You've got `registerMutationListener` that will tell you when a node has been created, updated and deleted and you can use Vanilla JS to interact with the DOM and do the appropriate modifications.

However, there may be cases when depending on what you want to render you may still want to use a DecoratorNode for the sake of simplicity (and yes, a DecoratorNode can be inline)

**Comment by seanchambo** [comment]
What is the best way to get the DOM element for a node in the `registerMutationListener` method?

**Comment by Benbinbin** [comment]
I also want to know the best practice of how to fetch data then update the node withou using DecoratorNode (that say not rely on React)

maybe this topic #4718 can be a case shown at Lexical Documentation
