### ISSUE TITLE
Feature: Make collaboration plugin support IndexeddbPersistence

### ISSUE THREAD

**Issue by zephyraft** [facebook/lexical#3085]
I'm trying to add IndexeddbPersistence to the providerFactory of the collaboration plugin, so that the offline content can be saved in the local browser.
When I try something like the following code, it works fine without switching the namespace of LexicalComposer.
```
<LexicalCollaborationPlugin
    id={id}
    username={username}
    providerFactory={(id, map) =>
        let doc = map.get(id);
        if (doc === undefined) {
            doc = new Y.Doc();
            map.set(id, doc);
        } else {
            doc.load();
        }

        const _doc = doc;

        return new (class extends WebsocketProvider {
            private _indexeddbProvider: IndexeddbPersistence;

            constructor() {
                super(websocketAddr, id, _doc, {
                    connect: false,
                });
                this._indexeddbProvider = this.bindIndexeddb(id, _doc);
            }

            private bindIndexeddb(id: string, doc: Y.Doc) {
                const indexeddbPersistence = new IndexeddbPersistence(id, doc);
                indexeddbPersistence.whenSynced.then((persistence) => {
                    console.debug(
                    'loaded data from indexed db',
                    this.roomname
                    );
                });
                return indexeddbPersistence;
            }

            connect() {
                super.connect();
                this._indexeddbProvider = this.bindIndexeddb(this.roomname, this.doc);
            }

            disconnect() {
                super.disconnect();
                this._indexeddbProvider.destroy();
            }
        })();
    }
    shouldBootstrap={!skipCollaborationInit}
/>
```

However, **when the websocket connection fails, the document cannot be switched normally when the namespace is modified**.

https://github.com/facebook/lexical/blob/f0de0f57dd5f7f5ec04caf1449259cbc6230d060/packages/lexical-react/src/shared/useYjsCollaboration.tsx#L56

the doc state in `useYjsCollaboration` will only setDoc when the WebsocketProvider triggers the reload event, so when the websocket connection fails, the document will not switch properly.

Finally I tried adding the following code to `useYjsCollaboration` to make it work.
```
useEffect(() => {
    const newDoc = docMap.get(id);
    if (newDoc) {
        setDoc(newDoc);
    }
}, [id, docMap]);
```

Hope the collaboration plugin will add support for indexeddb or other providers.

**Comment by fantactuka** [comment]
Could you explain what do you mean with "with/without switching the namespace"?

In general, Lexical collaboration is not tied to any specific adapter, it only needs connect/disconnect methods and couple events to be emitted. Internally that provider can initialize WS connection + IDB storage as a backup

**Comment by zephyraft** [comment]
Thanks for the reply, the namespace mentioned in the issue refers to the namespace property in the initialConfig of LexicalComposer.
According to my understanding, modifying the namespace can switch from document A to document B.
As you said, the collaboration should not depend on any particular adapter, when not modifying the state of the component, it should work fine.
At present, the problem I am encountering is the switching of documents. When I try to implement the function of switching document A to document B (modifying the namespace), the document cannot be switched when the websocket connection is not successfully established and only indexeddb is used to provide offline persistence capabilities.

**Comment by EgonBolton** [comment]
I am a bit lost. Is the CollaborationPlugin designed to only work with y-websocket? How could other providers be used?

**Comment by joakim** [comment]
`CollaborationPlugin` appears to be made for the `y-websocket` provider specifically. AFAIK, it shouldn't be too hard to make it work with any Yjs provider.

There are broadly speaking two types of Yjs providers:
- Connection providers (`y-websocket`, `y-webrtc`, `y-dat`, …)
- Database providers (`y-indexeddb`, `y-leveldb`, `y-redis`, …)

`y-indexeddb` is typically used for in-browser persistence alongside a connection provider, typically `y-websocket`. But it could just as well be the only provider if all you needed was persistence, without collaboration.

Collaboration is only one aspect of Yjs. It would be really nice to be able to mix and match any Yjs providers, whether for collaboration or for persistence. Maybe rewrite `CollaborationPlugin` to be connection provider agnostic, and introduce a `PersistencePlugin` for database providers?

**Comment by fantactuka** [comment]
> CollaborationPlugin appears to be made for the y-websocket provider specifically.

Not really, although code would need a bit of a cleanup from `WebsocketProvider` and instead use Provider interface:
https://github.com/facebook/lexical/blob/3d1dd923b8f5f32990cfca047c90a4b0c4d49f69/packages/lexical-yjs/src/index.ts#L37-L49

If your provider follows this interface, it'll work fine. There's no need to touch `CollaborationPlugin`, instead provide custom factory for your provider that internally can initialize any (or multiple at a time) mentioned above.

E.g., initialize IDB with WS:

```js
export function createWebsocketProvider(
  id: string,
  yjsDocMap: Map<string, Doc>,
): Provider {
  let doc = yjsDocMap.get(id);

  if (doc === undefined) {
    doc = new Doc();
    yjsDocMap.set(id, doc);
  } else {
    doc.load();
  }

  const idbProvider = new IndexeddbPersistence(id, doc);

  const wsProvider = new WebsocketProvider(
    WEBSOCKET_ENDPOINT,
    WEBSOCKET_SLUG + '/' + WEBSOCKET_ID + '/' + id,
    doc,
    {
      connect: false,
    },
  );

  return wsProvider;
}
```

**Comment by joakim** [comment]
Nice, thanks for the clarification and the follow-up PR!

**Comment by EgonBolton** [comment]
@fantactuka I'm still lost. Your idbProvider variable is not used anywhere.

shouldn't createWebSocketProvider return something like an array of providers, or are they registered just by creating the instance?

Also, in case all providers need to be returned, I'm seeing that IndexeddbPersistence doesn't match the interface provider.

**Comment by EgonBolton** [comment]
Regarding the last point, I'm seeing that `y-websocket` doesn't match the interface provider either (the playground is using `// ts-ignore`).
I don't know if this has a reason for being or if the interface Provider should be modified.

**Comment by fantactuka** [comment]
> @fantactuka I'm still lost. Your idbProvider variable is not used anywhere.

Here's a bit updated version:

```js
function createWebsocketProvider(
  id: string,
  yjsDocMap: Map<string, Doc>,
): Provider {
  let doc = yjsDocMap.get(id);

  if (doc === undefined) {
    doc = new Doc();
    yjsDocMap.set(id, doc);
  } else {
    doc.load();
  }

  const idbProvider = new IndexeddbPersistence(id, doc);

  const wsProvider = new WebsocketProvider(
    WEBSOCKET_ENDPOINT,
    WEBSOCKET_SLUG + '/' + WEBSOCKET_ID + '/' + id,
    doc,
    {
      connect: false,
    },
  );

  return {
    connect() {
      idbProvider.connect();
      wsProvider.connect();
    },

    disconnect() {
      idbProvider.connect();
      wsProvider.connect();
    },

    on(event, callback) {
      ...
    },

    off(event, callback) {
      ...
    },

    // idbProvider does not do anything with awareness
    awareness: wsProvider.awareness,
  }
}


```

> shouldn't createWebSocketProvider return something like an array of providers, or are they registered just by creating the instance?

I don't think we'll do much by allowing list of providers. Depending on what provider does it can be combined with other providers in different ways. E.g., in example above idb provider does not handle awareness updates (cursor position and presence), while ws provider synchronizes it. So it's up to application that would define how providers will communicate with each other, and return "wrapper" provider as above.

> Regarding the last point, I'm seeing that y-websocket doesn't match the interface provider either (the playground is using // ts-ignore).

Lexical's Provider interface expects that awareness will include some of required fields (color, name, anchorPos, focusPos) as collab plugin relies on those to render cursor. While y-websocket awareness is not more lose `{ [string]: any }`. 

To avoid ts-ignore we could've added wrapper provider that would proxy all calls to y-websocket one and do extra type checking for awareness.setLocalState/awareness.getStates

**Comment by EgonBolton** [comment]
Thank you for your answer @fantactuka.

Have you tried that code? It does not work for me.

I've gotten indexedDB and y-websocket to work using the snippet from your penultimate message. Apparently, setting the wsProvider to `{ connect: false }` was important, something that wasn't obvious to me at least.

From what I can see the reason for this is that `CollaborationPlugin` handles some things like connecting and disconnecting the provider, which causes problems if the wsProvider is instantiated with connect set to true. Furthermore, it seems that all the handling that `CollaborationPlugin` does with the provider brings up some problems with other providers, as they tend to be very different from each other.

For example, the snippet from your last comment doesn't work, because the `idbProvider.connect()` method doesn't exist. Apparently the configuration in your penultimate message works because indexedDB is a particular case in which it is registered by instantiating the class. But considering what I just said, I don't know if this would work with, for example, nested editors (since it's something that the provider returned in providerFactory takes care of). Could you confirm?

Nor can I find a way to register for example, only indexedDBPersistence (without y-websocket), or Hocuspocus (provider for which [I have already opened a feature request](https://github.com/facebook/lexical/issues/4351)).

It seems that `CollaborationPlugin` is very tied to y-websocket.

I have created a small repository [here](https://github.com/EgonBolton/collab). I would greatly appreciate it if you could tell me how I can connect to IndexedDB + Hocospocus, or if you could guide me towards the path. But my impression is that work should be done on making `CollaborationPlugin` more "provider-agnostic".

**Comment by hum-sc** [comment]
For whoever it would help, I got a similar issue getting `y-indexeddb` to work alongside with collab plugin and `y-websocket`, what it happends to my code was that when I tried to load the document, the local yjs tree were not synced into lexical, so the local changes were not rendering in the editor, but new changes were merged properly.
After reading code and logs, I found that the order `IdexeddbPersistence` get synced for the first time impact directly on wheter it works properly or not, and it is all because if it get synced before the observer `onYjsTreeChanges` is registered, then the local Yjs tree is never synced with Lexical state, then I fixed it by mooving the cration of the `IdexeddbPersistence` into the connect method of my custom Provider instead of the constructor.
 ```ts
constructor(path:string, doc:Y.Doc, id:string){
        this.wsProvider = new WebsocketProvider(path, id, doc, {
            connect: false,
        });  
        this.awareness = this.wsProvider.awareness as unknown as ProviderAwareness;
    }
    connect() {
        const idbProvider = new IndexeddbPersistence(this.wsProvider.roomname, this.wsProvider.doc);
        this.wsProvider.connect();
    }
```

I think, as `y-indexeddb` provider did not have a method `connect`, if you make your custom Indexeddb provider this would not be a problem.
