### ISSUE TITLE
Feature: editor.registerCommandsListener 

### ISSUE THREAD

**Issue by strdr4605** [facebook/lexical#3158]
Based on 
- https://github.com/facebook/lexical/discussions/3151

I would like to register a listener for any command that was dispatched by the editor.

```js
editor.registerCommandsListener((commandType, payload, priority) => {
  // do something here
})
```

Probably this means that we will have to change the createCommand function:

```js
export function createCommand<T>(type: string): LexicalCommand<T> {
  return { type };
}
```

Maybe this feature requires 2 functions, `registerBeforeCommandsListener` and `registerAfterCommandsListener`? 🤔
Or 2 callbacks to `editor.registerCommandsListener`.

## Alternative

Get all know commands and register a listener

```js
const allEditorCommands = [
  ...lexical.Commands,
  ...project.Commands,
  ...otherInstalledPlugins.Commands
];

for (const command of allEditorCommands) {
  editor.registerCommand(command, (payload) => {}, COMMAND_PRIORITY_EDITOR)
}
```

**Comment by thegreatercurve** [comment]
I wouldn't mind us adding a string type to the `createCommand` method. There's a related PR which adds this functionality here (#2942), awaiting review, because we need the string types for logging in the upcoming developer tools web extension.

I'm not sure we should have one all encompassing command listener though. This was how `registerCommand` used to work, but we took it out, in favour of registering commands individually (see #1551).

We found having one command listener created a lot of unnecessary additional callbacks for every command, forcing developers to add lengthy conditional/`switch` statements to check for the command types. Plus, it made typing the command types with the payload slightly more difficult.

I think the best approach is to add string types to the commands. You can then register commands with their callbacks as outlined in your alternative approach: 

```js
editor.registerCommand(
    command, 
    (payload) => analytics.track({ event: command.type }), 
    COMMAND_PRIORITY_EDITOR
)
```

**Comment by strdr4605** [comment]
Then should we have an array of commands exported from lexical or any other custom plugin?

**Comment by thegreatercurve** [comment]
@strdr4605 Can you just import the commands you need one-by-one, instead? We have a few default commands in the core (e.g.`CONTROLLED_TEXT_INSERTION_COMMAND` or `CAN_REDO_COMMAND`) which are more to do with the core business logic, and probably wouldn't have much purpose for analytics.

**Comment by strdr4605** [comment]
Ok 😊
