### ISSUE TITLE
Bug: `SELECTION_CHANGE_COMMAND` event is not fired on node selection

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3160]
Listeners of the `SELECTION_CHANGE_COMMAND` command do not receive events if the selection changes to a node.

Lexical version: 0.5.0

## Steps To Reproduce

1. Use the modified codesandbox example that listens for the event
2. Add some text and horizontal rules (HR button in the toolbar)
3. Do any text selection - in the console, you will see `SELECTION_CHANGE_COMMAND, RangeSelection(...)` output
4. Select horizontal rule - click on it (which is hard 🙈 ) or select using keyboard (set cursor to the start of a paragraph next to it and press ArrowLeft). When the node is selected it is reflected in the history plugin, however, the console log does not output anything.

Link to code example: https://codesandbox.io/s/busy-wing-1eop87

https://user-images.githubusercontent.com/1575198/195141496-f174784b-802a-4f07-80d8-2d0f6aecd5e0.mov

## The current behavior
Decorator node selection is not captured and does not trigger `SELECTION_CHANGE_COMMAND` event.

## The expected behavior
Whether it is a range -> node selection change or node -> node it should trigger the `SELECTION_CHANGE_COMMAND` event.

**Comment by Piliuta** [comment]
> I encountered the same problem, any solution?

I ended up using `registerUpdateListener` https://lexical.dev/docs/concepts/listeners#registerupdatelistener instead of listening for the command. This fixed some issues on my end, although I am not sure if there are any downsides for using it (I did not notice so far).

**Comment by LvChengbin** [comment]
@Piliuta I tried that too, but it doesn't work while using nested editors. I need to listen to `SELECTION_CHANGE_COMMAND` event to get the current active editor and it isn't triggered.

**Comment by LvChengbin** [comment]
@Piliuta  I tried triggered the `SELECTION_CHANGE_COMMAND` by myself and solved my problem by a hack. `Lexical` has some strange code to handle the `selection` and `editor._selection`, it's messy and need to be re-designed and optimized.

**Comment by LvChengbin** [comment]
Does any plan on this issue? My hack code doesn't work after updating lexical to the latest version.

**Comment by trueadm** [comment]
We should probably invoke a SELECTION_CHANGE_COMMAND in the update phase where we trigger update listeners if going from RangeSelection -> NodeSelection by comparing prevSelection to nextSelection. I wonder if we should also invoke if NodeSelection's selected nodes change too?

**Comment by LvChengbin** [comment]
@trueadm It may still not work. You can try the following steps:

1. add an `image` in playground and paste another `image` into the nested editor of the image's caption.
2. Click the image in caption nested editor for selecting it.
3. Click the first image.

The image in caption doesn't be deselected while clicking into another editor (nested editor or parent editor).
I think the reason of this issue is because the `registerUpdateListen` event can't be triggered while click into another editor, and the code below can't been executed.

https://github.com/facebook/lexical/blob/ec18fcf2c22b30a22ef161d3b579a635c9095bcc/packages/lexical-react/src/useLexicalNodeSelection.ts#L44
