### ISSUE TITLE
Bug: Empty text node inserted after DecoratorNode at the root

### ISSUE THREAD

**Issue by Stopa** [facebook/lexical#3307]
Lexical version: 0.6.0

## Steps To Reproduce

In certain setups with DecoratorNodes, an empty TextNode is being added where it shouldn't be.

Link to code example:

https://codesandbox.io/s/practical-aryabhata-iwy63q?file=/src/App.js

## The current behavior

With the structure outlined in the above code example, an empty text node is added after ChapterTagsNode. It's not visible in TreeViewPlugin. Note that in below image, the node is focused, but TreeViewPlugin doesn't show where the selection is.

![image](https://user-images.githubusercontent.com/408256/199518484-76ca9abf-d84f-4a02-bec0-d7a110582bce.png)

But the user is able to focus it and write text, which creates a new empty TextNode as child of the RootNode.

![image](https://user-images.githubusercontent.com/408256/199518534-7db97294-8029-4737-98bc-70c44b09e851.png)

## The expected behavior

No such "ghost" node should be added.

**Comment by abelsj60** [comment]
@Stopa I don't know if you have solved this to your satisfaction, but I forked it and quickly added some code that could help you solve it if you haven't gotten a chance to do it yourself yet. I figured it would only take a couple minutes.

I had to work with commands this weekend and suspected I found your problem along the way. 

If you haven't seen it, I think this insertion is caused by the `CONTROLLED_TEXT_INSERTION_COMMAND`.

It seems to govern the insertion of the first piece of text on an otherwise empty line. You might have to handle more commands, too, such as the `KEY_MODIFIER_COMMAND`. I'm not sure. Thing is, once you muck around with Lexical's core commands, you have to handle all the related cases on your own, too. Try everything...!

I'm not sure the insertion behavior's a bug or just a rough edge that could be improved or better documented. Anyway, I saw you ask for expedited help in Discord, so figured... See the `NoRandomInsertionsPlugin` on line 91 for my take. 

Hope it helps.

https://codesandbox.io/s/old-currying-nht5j4?file=/src/App.js:2688-2728

-j

**Comment by trueadm** [comment]
We are clearly missing an invariant that should prevent the TextNode from being added to the RootNode.

**Comment by abelsj60** [comment]
> We are clearly missing an invariant that should prevent the TextNode from being added to the RootNode. I'll see if I can tighten this up a bit.

lol. You're a much smarter man than me. I just hammered a fix into place, but I can see you're right..!

**Comment by trueadm** [comment]
@Stopa I can't see an empty text node. I can see a `<br>` though. If you mark your decorator as `isInline() { return false }` and wait for https://github.com/facebook/lexical/pull/3406, this should hopefully fix your problem.

**Comment by denone** [comment]
> @Stopa I can't see an empty text node. I can see a `<br>` though. If you mark your decorator as `isInline() { return false }` and wait for #3406, this should hopefully fix your problem.

@trueadm you meant `isInline() { return true }` 🙂 ?

**Comment by trueadm** [comment]
@denone This is a block element by looking at the codesandbox, so inline should be `false`.

**Comment by denone** [comment]
> @denone This is a block element decorator by looking at the codesandbox, so inline should be `false`.

Thanks, it works 👍

**Comment by Stopa** [comment]
@trueadm thank you for clearing this up! @denone is my colleague who is dealing with this project currently so if he says it's fixed, this issue can be closed :)
