### ISSUE TITLE
Bug: Copying content from tables in plain text is broken

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#3416]
![Screenshot 2022-11-24 at 12 39 32](https://user-images.githubusercontent.com/1519870/203786786-3ed925b9-d3dc-4767-94f4-d2a509022d71.png)

Copying this results in plain text being added which is completely wrong;

```












a

b

c





d

e

f























a

b

c

aaabbbccc

d

e

f

dddeeefff
```

**Comment by icrosil** [comment]
Hey, just tried to repro this issue and it seem behaviour has changed and now cells selected in table are not being copied at all. I assume that's expected behaviour and since it's not harming - it is just not allowing copy - looks fine.

@thegreatercurve @zurfyx please chime in if intended behaviour is different.
