### ISSUE TITLE
Feature: Improving selection around decorator nodes

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#3426]
Today, there are a variety of issues with selection and Lexical's decorator nodes.

- Block level decorator nodes can block selection from happening at all. https://github.com/facebook/lexical/issues/3417
- Inline level decorator nodes cause selection to appear in the wrong place or to be lost entirely.
- The cursor often doesn't show in the right place.

Taking inspiration from ProseMirror, we can opt to use two tricks to get around these problems:

- Have a virtual emulated cursor which is just a non editable div with no content that shows a horizontal cursor. This would be applied by the reconciler between boundaries of block level decorator elements. This fixes the first issue and the third issue.
- Use images without a src to be handled by the reconciler. These allow selection and the cursor to be shown in the right place. The images would be inserted around decorators that are block level (have no text next to them).

The complexity of this task is implementing this elegantly into the existing reconciler and teaching the selection system to identify and ignore these special elements we insert into the DOM.

Hopefully this should fix the many issues open around this problem space: https://github.com/facebook/lexical/issues/3417 https://github.com/facebook/lexical/issues/1965 https://github.com/facebook/lexical/issues/3156 https://github.com/facebook/lexical/issues/3157 https://github.com/facebook/lexical/issues/3143 https://github.com/facebook/lexical/issues/2285

**Comment by mehmetscoskun** [comment]
I have a case where the images are like block and they are rendered at the same level with paragraphs. You cannot add text next to it. My problem was that I could not put my cursor between images. I fixed that with these steps:
- I added `::before` (top) and `::after` (bottom) pseudo elements to the image.
- I gave them enough heights, so that they look like margins.
- I added a `NodeEventPlugin` with click for the image nodes. When you click those pseudo elements:
           - it moves selection to before/after the image node, if there is some text. 
           - it creates a paragraph node before/after the image node, if there is no text and moves selection there.

In this fix, if you move cursor afterwards, it does not remove the paragraph node you just created but that's fine by me.
