### ISSUE TITLE
Bug: registerUpdateListener gives stale state after clearing formatting

### ISSUE THREAD

**Issue by TrySound** [facebook/lexical#3456]
Lexical version: 0.6.4

## Steps To Reproduce

1. make bold non-first word
2. click on clear
3. editorState still gives bold format

Link to code example:

https://codesandbox.io/s/mutable-browser-tsk7n2?file=/src/App.tsx

## The current behavior

Bold state is not reset after clearing formatting

## The expected behavior

Bold state is set to false after clearing formatting

**Comment by thegreatercurve** [comment]
@TrySound Remove the `useCallback` around `updateToolbar` and then it works as expected, or make `updateToolbar` accept a selection argument: 
```
 const updateToolbar = useCallback((selection) => {
    if ($isRangeSelection(selection)) {
      setIsBold(selection.hasFormat("bold"));
    }
  }, []);
```
The problem is the callback is being memoized with the same stale selection, so doesn't correctly get the new selection when you call `editor.read`. 

Tested this out in your CodeSandbox and verified that the toolbar button updates as expected

**Comment by TrySound** [comment]
Hi @thegreatercurve. I removed useCallback and inlined the code instead. The issue still reproduced. I updated codesandbox.
<img width="248" alt="image" src="https://user-images.githubusercontent.com/5635476/204665816-0938caa9-15dd-4c5f-a937-f7054d7021e4.png">
