### ISSUE TITLE
Feature: how to use in webview?

### ISSUE THREAD

**Issue by moyang-pro** [facebook/lexical#4000]
I want to define a function for android to use, such as fetching HTML data, but the current interface cannot be implemented

**Comment by thegreatercurve** [comment]
What current interface is causing issues?

**Comment by moyang-pro** [comment]
> @moyang-pro What current interface is causing issues? The library should work in a web view.

I want to get an editor instance on web view interfce and get html by lexical interface

**Comment by christhoph** [comment]
> > @moyang-pro What current interface is causing issues? The library should work in a web view.
> 
> I want to get an editor instance on web view interfce and get html by lexical interface

Hi @moyang-pro, I have a couple of doubts here:
1. what you want is you can show the lexical editor in android using a webview?
2. Or add an action that pulls the lexical editor state into HTML on button press?

I think it's the 2nd option from what I understand, I recently implemented something similar. I had to store a previous instance of the editor state to restore it on a button press in the app, I think that might help you.

For this we must understand how we can communicate the web in the webview with the app:
https://www.educative.io/answers/how-to-communicate-with-data-between-webviews-in-react-native

With this in mind, we must define the logic to be able to send and receive events in both directions.

#### Website

- Send events

All the information that is sent to the application must be a string: `WebViewMessage.data: string`, so if the information that you must send is not a string, you can use the `JSON.stringify` to convert it:

```js
const emitEvent = (event) => {
  window.ReactNativeWebView.postMessage(JSON.stringify(event));
};
```

When using it, you can only send the information you need or you can create `types` or `events` to be able to identify different events, as required. For example:

```js
const htmlString = $generateHtmlFromNodes(editor, selection | null);

emitEvent({ type: 'lexical-html', data: htmlString });
```

> ref: https://lexical.dev/docs/concepts/serialization#html

- Receive events

Here you need to register the `message` event to be able to listen to the events that are sent from the app, although there is an issue about using `document` or `window` depending on the OS of the device. So you have to add a validation to use `document` in Android and `window` in iOS.

```js
const entity = navigator.userAgent.match(/Android/i) ? document : window;

entity.addEventListener('message', nativeMessageListener);
```

> ref: https://stackoverflow.com/a/58118984

The listener to receive the data is quite simple and will also depend on the structure that you define when sending the event from the app.

```js
const nativeMessageListener = (message) => {
  const nativeData = JSON.parse(message.data);

  // You can create a switch or if statements for the types or events that are defined
  if (nativeData.type === 'request-html') {
    // here would go the action that we previously defined to send the data to the app
  }
};
```

All this can go inside a `useEffect`.

#### Mobile app

- Send events

In order to send events we need to create a ref and link it to the webview containing the editor:

```js
const editorWebviewRef = useRef();

return (
  <WebView
    source={{ uri }}
    ref={editorWebviewRef}
    injectedJavaScriptBeforeContentLoaded={runBeforeFirst}
  />
);
```

With this we can define a function quite similar to the previous one where using the webview ref we execute the postMessage method and send the event.

```js
const emitMobileEvent = (event) => {
  if (contentCreatorWebviewRef.current) {
    contentCreatorWebviewRef.current.postMessage(JSON.stringify(event));
  }
};
```

Here we can only define a type that is identified in the webview listener to execute an action:

```js
emitMobileEvent({ type: 'request-html' });
```

- Receive events

To receive the events from the webview you can get these events in the `onMessage` prop:

```js
const handleWebViewEvents = (ev) => {
  const event = JSON.parse(ev.nativeEvent.data);

  // here the event that is emitted in web would be received
  if (event.type === 'lexical-html') {
    const { data } = event;

    // do something
  }
};

return (
  <WebView
    source={{ uri }}
    ref={editorWebviewRef}
    onMessage={handleWebViewEvents}
    injectedJavaScriptBeforeContentLoaded={runBeforeFirst}
  />
);
```

___

I hope this can be of help, the flow of this behavior would be:

1. In the app, the button is pressed and the `request-html` event is emitted to the webview
2. The webview listens for the `request-html` event, executes the logic that is required, and emits an event `lexical-html` to the app.
3. The app receives the `lexical-html` event and executes some action with the received data
