### ISSUE TITLE
Bug: history undo causes the decorator node to refresh

### ISSUE THREAD

**Issue by 1943time** [facebook/lexical#4020]
react history plugin execute undo decorator node will re-execute the decorate method, So the component state cannot be preserved

**Comment by thegreatercurve** [comment]
This is generally by design. Lexical isn't a React framework, it's a vanilla JS framework with React bindings. If you want to preserve state after an editor update, you can store values directly on the decorator node itself and then pass them down to the component within the `decorate` method. A good example of this is the ImageNode: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ImageNode.tsx
