### ISSUE TITLE
Bug: Selected DecoratorNode prevents typing

### ISSUE THREAD

**Issue by sodenn** [facebook/lexical#4495]
Lexical version: 0.10.0

## Steps To Reproduce

1. Open https://codesandbox.io/s/wild-cdn-fkop2n?file=/src/nodes/BoxComponent.tsx (lexical@0.10.0)
or open the Images Plugin example: https://lexical.dev/docs/demos/plugins/images (lexical@0.5.0)
2. Start typing and insert a box/image in the middle of the text. Then place the cursor beside the box/image and use the arrow keys to select it.

Now, navigating with the arrow keys no longer works and typing is not possible. The selection now remains on the DecoratorNode.

## The current behavior
The selection remains on the DecoratorNode when navigating with the arrow keys.
![2023-05-14 19 29 17](https://github.com/facebook/lexical/assets/232054/78ad7d72-683e-4acd-b37a-ada44b080fec)

## The expected behavior
The selection should be removed from the DecoratorNode when navigating with the arrow keys.

**Comment by thegreatercurve** [comment]
This is because you're applying the native browser/range selection within the `contenteditable=false` which means the arrow keys will no longer work. 

Use the `KEY_ARROW_LEFT` and `KEY_ARROW_RIGHT` commands to overwrite this native behaviour and apply the node selection directly to the Box. 

We do something similar in the HorizontalRule plugin.
