### ISSUE TITLE
Bug: React Decorator nodes constantly remounting

### ISSUE THREAD

**Issue by jeffsee55** [facebook/lexical#4605]
I've noticed that Decorator nodes seem to remount on React state update. I can't reproduce the behavior in the Playground in the Lexical monorepo but was able to do it in a code sandbox. Pressing the "Click Me" button causes the `ImageNode` to remount. 

To reproduce:

https://codesandbox.io/p/sandbox/sad-thunder-lkt6sr?file=%2Fsrc%2FApp.tsx%3A83%2C1

Debugging:

Note you need to view the console to see the "mounted" message, full screen version here https://lkt6sr-5173.csb.app/

**Comment by thegreatercurve** [comment]
This is generally by design. Lexical isn't a React framework, it's a vanilla JS framework with React bindings. If you want to preserve state after an editor update, you can store values directly on the decorator node itself and then pass them down to the component within the decorate method. A good example of this is the ImageNode: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ImageNode.tsx

**Comment by fantactuka** [comment]
The reason decorators are getting remounted is your ErrorBoundary is defined as an inline function. So either wrap it into useCallback/useMemo or extract from the component to avoid re-creating new function on each composer re-rendering
