### ISSUE TITLE
Bug: issue when multiple editors are on the same page and a node transform "listener" is used

### ISSUE THREAD

**Issue by ifrim** [facebook/lexical#4853]
If multiple editors are on the same page and `registerNodeTransform` is used the focus **jumps** to the last "touched" editor.
If `registerNodeTransform` is not used the behavior is as expected.
There doesn't need to be an implementation for the callback passed to `registerNodeTransform`. Also it doesn't seem to matter which node is given either. It is the same with TextNode, ParagraphNode or RootNode.

**Lexical version**: 0.11.3

## Steps To Reproduce

1. Create an editor component with lexical that uses registerNodeTransform
2. Add 2 or more instances of the editor on the same page
3. Add an action that updates the state of the parent of the editors
4. After focusing at least two editors trigger that action
5. Observe

Link to code example:
repo that reproduces the issue: https://github.com/ifrim/lexical-node-transform-listener-issue

## The current behavior
When a rerender of the parent is triggered (e.g. by clicking a button that updates some state) the focus is moved to the last editor that was previously focused at least once.
If there are editors that haven't been "touched" yet they will not be the target of the focus "jump".

## The expected behavior
When a rerender of the parent is triggered the focus should not move between editors.

## Video
In the video example there is a plugin with this implementation:
```js
function TextTransformPlugin() {
    const [editor] = useLexicalComposerContext();
    useEffect(editor.registerNodeTransform(TextNode, () => {}), []);
}
```
The simple presence of `editor.registerNodeTransform()` triggers this behavior.

https://github.com/facebook/lexical/assets/5877494/2fe08493-e7b9-47de-8758-8937d995e002

**Comment by acywatson** [comment]
This is weird - thanks for the detailed report!

**Comment by moy2010** [comment]
I have dived a bit into the issue, and this is what I've found so far (just stating some facts):

1. There's no way to determine the current active editor (at least in React). Or in other words, the active editor is changed under the carpet and React has no way to know about it.

These are the things that I tried so far:

## 1. Observe the TreeView for hints on the history of commands

The steps to reproduce the bug are:

1. Focus on `editor1`
2. Select some text
3. Send the command to **bold** the text selection
4. Focus on `editor2`
5. Select some text
6. Send the command to **bold** the text selection

After step #6, these are the commands shown in `editor1` Tree view:

```
  commands:
  └ { type: SELECTION_CHANGE_COMMAND, payload: undefined }
  └ { type: CLICK_COMMAND, payload: PointerEvent }
  └ { type: SELECTION_CHANGE_COMMAND, payload: undefined }
  └ { type: CLICK_COMMAND, payload: PointerEvent }
  └ { type: CUSTOM_FORMAT_TEXT_COMMAND, payload: bold }
  └ { type: CAN_UNDO_COMMAND, payload: true }
  └ { type: SELECTION_CHANGE_COMMAND, payload: undefined }
  └ { type: CUSTOM_FORMAT_TEXT_COMMAND, payload: bold }
  └ { type: CAN_UNDO_COMMAND, payload: true }
  └ { type: SELECTION_CHANGE_COMMAND, payload: undefined }
```

## 2. Use a reference to the active editor (`useRef`) instead of state (`useState`) to avoid using a stale editor when dispatching the command

As you could guess from my initial comment, this didn't work because Lexical is changing the active editor under the carpet, so React could not observe it.

## 3. Using the registerRootListener to try to determine the active editor before the command is dispatched

This third approach didn't work either :man_shrugging:, and is the one that left me even more confused. The point is that the editor that is used when dispatching the command is changed under the carpet, **even before registerRootListener has a chance to run**!

I hope that these findings are helpful to determine what's going on.

**Comment by moy2010** [comment]
I have tested again in latest version (0.12.4) and the bug seems to be gone. Could you verify this, @ifrim?

**Comment by ifrim** [comment]
@moy2010 I updated lexical to version 0.12.4 in the example repo linked in the issue and unfortunately the problem is still reproducing :(

**Comment by moy2010** [comment]
I see :(. Then your case is different than mine. In my case, having multiple editors opened at the same time exhibited a behaviour like the one that you described initially (with certain editor updates going to the wrong editor), but now is working as expected.

**Comment by ak1394** [comment]
I think I've run into the same issue: I've several lexical instances on the page, larger one at the top and few one-line ones which used to edit just a single line of the text.

To prohibit user from entering multi-line text into single-line editors I use this:

```js
export default function RemoveLinebreaksPlugin() {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    return editor.registerNodeTransform(LineBreakNode, (node) => {
      node.remove();
    });
  }, [editor]);

  return null;
}
```

If the text in the first editor is modified, it starts to steal focus from the single-line instances.

I'm on version 0.13.1

**Comment by ak1394** [comment]
I was wrong blaming the issue on registerNodeTransform(), in my case something else causes the issue. I will update the issue if I manage to narrow it down.

**Comment by ak1394** [comment]
I've tracked it down to the use of useLexicalTextEntity() which in turn calls registerNodeTransform(). So my issue is indeed the same as the original one.

**Comment by lucasrothman** [comment]
Having a similar issue and the workaround to only render the plugin if focused isn't working for me either. Is there an update to this issue or a better workaround?

**Comment by etrepum** [comment]
I know this is old, but since there have been recent comments I decided to take a look. As far as I can tell this is because your plugin is implemented incorrectly such that you're registering a new transform on every render which causes the editor to become dirty and reconcile its focus (and will eventually cause your app to slow to a crawl).

```diff
diff --git a/src/editor/editor.jsx b/src/editor/editor.jsx
index e4b0543..680473d 100644
--- a/src/editor/editor.jsx
+++ b/src/editor/editor.jsx
@@ -11,7 +11,7 @@ import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary';
 function TextTransformPlugin() {
        const [editor] = useLexicalComposerContext();
 
-   useEffect(editor.registerNodeTransform(TextNode, () => {}), []);
+   useEffect(() => editor.registerNodeTransform(TextNode, () => {}), [editor]);
 }
 
 function Editor({ withPlugin, withOnChange, onChange }) {

**Comment by ak1394** [comment]
Thanks for having a look @etrepum ! I think it's a different issue in my case though. I'll try to reproduce the problem with the latest release of lexical and provide a standalone example. BTW, was surprised to see your name in the thread, was using your mochiweb in a project years ago... Kudos for that one!

**Comment by ifrim** [comment]
wow, such a silly mistake
thanks for taking a look @etrepum, confirming that this was the issue

**Comment by EzekielEnns** [comment]
> I know this is old, but since there have been recent comments I decided to take a look. As far as I can tell this is because your plugin is implemented incorrectly such that you're registering a new transform on every render which causes the editor to become dirty and reconcile its selection (and will eventually cause your app to slow to a crawl, because you'll have N copies of the transform running for every update).
> 
> ```diff
> diff --git a/src/editor/editor.jsx b/src/editor/editor.jsx
> index e4b0543..680473d 100644
> --- a/src/editor/editor.jsx
> +++ b/src/editor/editor.jsx
> @@ -11,7 +11,7 @@ import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary';
>  function TextTransformPlugin() {
>         const [editor] = useLexicalComposerContext();
>  
> -   useEffect(editor.registerNodeTransform(TextNode, () => {}), []);
> +   useEffect(() => editor.registerNodeTransform(TextNode, () => {}), [editor]);
>  }
>  
>  function Editor({ withPlugin, withOnChange, onChange }) {
> ```

Adding to this for anyone else in my boat
I had this code which looks like it should work
```
  const pattern = useMemo(
    () => new RegExp(`(${p.matchRegex.source})(${p.delimiterRegex.source})`, 'i'),
    [p.matchRegex, p.delimiterRegex]
  );

  useEffect(() => {
    if (!editor.hasNodes([MatchNode])) {
      throw new Error('MatchNode: MatchNode not registered on editor');
    }

    return mergeRegister(
      editor.registerNodeTransform(TextNode, (node) => {
        if (!node.isSimpleText() || node.hasFormat('code')) {
          return;
        }
        const emailMatch = text.match(pattern);
      }),
    );
  }, [editor, pattern]);
```
it caused the focus to hope around just like described in the ticket
but when removing the pattern dep it works
```
  const pattern = useRef(new RegExp(`(${p.matchRegex.source})(${p.delimiterRegex.source})`, 'i'));

  useEffect(() => {
    if (!editor.hasNodes([MatchNode])) {
      throw new Error('MatchNode: MatchNode not registered on editor');
    }

    return mergeRegister(
      editor.registerNodeTransform(TextNode, (node) => {
        if (!node.isSimpleText() || node.hasFormat('code')) {
          return;
        }
        const emailMatch = text.match(pattern);
      }),
    );
  }, [editor]);
```

**Comment by etrepum** [comment]
Yes, regex literals are not interned (`/x/ !== /x/`) for the same reason that `[] !== []` or `{} !== {}`, they are mutable and have state. You can also lift those static regex definitions all the way to module level variables because they have no dependencies, will be more efficient without the need for `useMemo` or `useRef`
