### ISSUE TITLE
Bug:  https://lexical.dev/docs/error?code=20 was reported in the production environment

### ISSUE THREAD

**Issue by yuhe-talkdesk** [facebook/lexical#4963]
Lexical version: `0.10.0`

## Steps To Reproduce

Link to code example:

## The current behavior

In our production environment, in 20 days, different users reported a total of 18k articles about this error :  https://lexical.dev/docs/error?code=20
![image](https://github.com/facebook/lexical/assets/80082090/c085dea1-16b7-49a2-b9e8-1306031a0752)

But the weird thing is that we can't reproduce this error anyway, so does anyone know about this error?

**Comment by acywatson** [comment]
It's really hard to tell without some context. Point.getNode() is throwing, but without a line number and code context or something, it's pretty hard to know what might be going on.

I'm gonna close this because it's not actionable from our side. If you can provide a repro or any other info about it, we can reopen and dig deeper.
