### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by leonard-henriquez** [facebook/lexical#4997]
My team has been monitoring Lexical for more than a year. We are very excited about the project but so far we are reluctant to migrate from Prosemirror to Lexical because it hasn't released a stable version yet.
Do you have any ETA of when you could release v1 ?

**Comment by acywatson** [comment]
Good question - we have had a lot of internal discussion around this. We don't expect dramatic changes to the API anymore, at this point, so I would practically consider Lexical to be stable. As far as a 1.0, it seems like we can always find some reason to delay it, but in practice it's just a signal to the community of our confidence in the stability of the API, since we'll obviously still reserve the right to make changes between major versions.

I don't have a firm timeline for you, but I hope that context is helpful.
