### ISSUE TITLE
Bug: Format button on toolbar does not keep the correct state

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [facebook/lexical#5106]
The format isn't kept  when you click on empty paragraph. 
There is a clear gif to explain that: 

![CleanShot 2023-10-10 at 11 16 08](https://github.com/facebook/lexical/assets/30870051/747fdf94-0b27-47ce-91cc-e951daec8226)

Lexical version: Latest

## Steps To Reproduce

1. Go to https://playground.lexical.dev/
2. Remove everything on playground
3. Click on the bold format button
4. Click on any empty paragraph

## The current behavior
Actually, if we click on the format button and right after on any empty paragraph, the format button will be cancelled. 
But, if you click on the button then you write, everything looks "good"

## The expected behavior
If think, if you click on the format button, and on empty div then you write, the text should be in bold. (for example)

**Comment by funbinhe1996** [comment]
hi @Sebastien-Ahkrin I think this is expected behaviour. if you refer to `ToolbarPlugin`, you will figure it out.
In general, when you click, the Lexical will use the `selection` based on your click to update the `isBold` status,
so when you click on empty paragraph, it actually update the `isBold` to false as expected.
