### ISSUE TITLE
Feature: Configurable Text Wrapping to Allow Cleaner HTML Output

### ISSUE THREAD

**Issue by coltisor** [facebook/lexical#5220]
### Description
By default, Lexical wraps every bit of text in `<span>` tags with the `white-space: pre-wrap;` style. This behavior can be unnecessary for some use cases and leads to bloated HTML. A configuration option to disable this would be beneficial for cleaner HTML output.

![Lexical_Playground](https://github.com/facebook/lexical/assets/6502606/eeee055b-4659-47eb-ba7e-2637009ce936)

### Steps to Reproduce
1. Visit the [Lexical Playground](https://playground.lexical.dev/).
2. Enter some text into the editor.
3. Use the "Export DOM" function.

4. Observe that each text node is wrapped in a `<span>` with `style="white-space: pre-wrap;"`.

### Current Behavior
Text is automatically wrapped in spans with the `white-space: pre-wrap;` style. Here's an example of the current output:
```html
<h1 dir="ltr">
    <span style="white-space: pre-wrap;">Welcome to the playground</span>
</h1>
```

### Expected Behavior
The HTML output should be clean, without unnecessary styles or elements, like so:
```html
<h1>Welcome to the playground</h1>
```

### Proposed Solution
Implement a configuration option in Lexical that allows developers to choose whether text nodes are wrapped in spans with the pre-wrap style. By default, this could be set to the current behavior, but it could be disabled for cleaner HTML output.

**Comment by thegreatercurve** [comment]
@coltisorYou should be able to overwrite the core logic of some of the core nodes using the [node transform API](https://lexical.dev/docs/concepts/transforms), including `exportDOM`, though this isn't always guaranteed to work correctly. 

Otherwise, I would suggest just formatting the HTML yourself extracting it from the editor state, if you want to tidy up the formatting before saving to a database. 

We don't really want to start messing around with the in-built HTML formatting, as it really affects copy/paste compatibility between different editors, which is a common source of bugs.

**Comment by coltisor** [comment]
@thegreatercurve thank you for the answer. Now I get, RTE are more for good displaying than writing good markup. I will use something like https://www.npmjs.com/package/sanitize-html for my needs.
