### ISSUE TITLE
Feature: dompurify plugin for safe html ( useful against xss attack in both stored html and collaborative editing )

### ISSUE THREAD

**Issue by ys-oo** [facebook/lexical#5461]
i tried to test the security of lexical it's good but not perfect i was able to easily do xss attack on my application, i tried to write a custom plugin that will use dompurify package to clean the html , but I'm still new to this awesome framework , so i didn't succeed on creating perfect HTML sanitize plugin using dompurify, thank you <3 and i appreciate any help

**Comment by StyleT** [comment]
Hi! 
Can you provide some attack examples here?

**Comment by phillipngn** [comment]
@ys-oo Can you provide reproduction step?

**Comment by etrepum** [comment]
Closing since there is no reproduction. Please open a new issue with a reproduction if you can demonstrate an XSS issue that we should fix. By default the importDOM implementations for the nodes that ship with lexical are pretty conservative and won't import arbitrary styles and do not create nodes from HTML that they don't explicitly parse, so it's hard to see how this would generally be an issue unless you implement custom nodes that have their own security flaws.
