### ISSUE TITLE
Bug: Table deletion with keyboard works buggy

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#5543]
Lexical version: the latest (v0.12.6)

### when the last cell is empty:
1. go to the playground
2. enter table and make make the last cell empty
5. select table by keyboard(`shift` + `arrow keys`) and delete
7. now table and tablerow remains 
8. when you type something, it inserts text on tablerow directly.
 -> this triggers some bug. i.e. pressing ENTER breaks the editor as #5516

https://github.com/facebook/lexical/assets/40269597/566fdb02-396e-4e6e-9532-497ec7cf8d40

### even when the last cell is not empty
1. enter table
2. select table by keyboard with next sibling as anchor
3. delete
7. now table remains 
8. when you type something, it inserts text on table directly.
 -> this triggers some bug. i.e. pressing ENTER breaks the editor as #5516

https://github.com/facebook/lexical/assets/40269597/730f5387-f348-4c2b-919b-6565bc094500

Link to code example:

## The current behavior
- delete remains table and tablerow
## The expected behavior
-  it cleans table and its children then inserts a new paragraph as we delete it by selecting with mouse

https://github.com/facebook/lexical/assets/40269597/57cfcd8a-b104-4f94-ad8b-d1eeb2aa3330

**Comment by 2wheeh** [comment]
This might be resolved completely after introducing scheme #3833

**Comment by 2wheeh** [comment]
- #3833

**Comment by ivailop7** [comment]
https://github.com/facebook/lexical/assets/7893468/b4bbf493-fe06-452e-91bc-0cfc87a33e7d

I started looking at this yesterday and I'm unsure on the right place to fix this in. Since deletion behaviour is different depending on the selection direction, as captured in the video, if it's top to bottom, it's leaves a 'table' and 'tablerow', if it's bottom to top, it leaves only 'table'. This issue is only when the selection for deletion ends (or starts) exactly on the last table cell. If the table is inbetween two paragraphs, deletion works correctly. 

@zurfyx can you point me in the right direction for fixing this. I started looking into modifying the deleteCellHandler, but unsure if this needs a different deletion approach.
