### ISSUE TITLE
How to keep formatting between lines?

### ISSUE THREAD

**Issue by nickschinestzki** [facebook/lexical#5620]
I'm trying to achieve a different behavior regarding the formatting between lines in the Lexical Editor.

### The current behavior
1. In an empty editor, the user starts adding formatting and styles in the editor (font-family, font-size, color, bold, italic, etc)
2. When you press `Enter` once, it will insert a new line, which will have an "unstyled cursor" but upon new typing, the styles and formatting are applied again to the text.
3. When you press `Enter` twice, the new line, separated by the other ones, will lose all of the previous formatting and styling, returning to the default. 

https://github.com/facebook/lexical/assets/33634787/b7fc7e60-0ce6-4d5c-be79-bea582a9a675

### The desired behavior
1. In an empty editor, the user starts adding formatting and styles in the editor (font-family, font-size, color, bold, italic, etc)
2. When pressing `Enter` regarding of how much times/lines, the styles and formats are preserved. The user doesn't have to select the font-family and font-size again (for example) every time he creates a new a paragraph.

How can I achieve this?

_Originally posted by @nickschinestzki in https://github.com/facebook/lexical/discussions/5619_

**Comment by moy2010** [comment]
It sound like you'll need to prevent the stop the propagation of the `Enter` button event (check Lexical's command pattern), and handle yourself the creation of new paragraph nodes to conserve the existing state.

**Comment by ivailop7** [comment]
@acywatson @zurfyx do we agree, this should be the default behaviour?

**Comment by acywatson** [comment]
> @acywatson @zurfyx do we agree, this should be the default behaviour?

I mean the trade off is now that you have the opposite problem. If a user wants to just bold one line or add several formats to one segment of text, they need to then clear all those formats off when they start typing on the next line.

I suspect the case of adding formats to a small portion of otherwise non-formatted text (or even typing the text non-formatted, then going back to apply formats to specific sections) is far more common than the case of setting a bunch of formats and typing multiple lines with those formats engaged.

Probably the perspective we should come from here, though, is what's the easiest way to set it up so a developer can easily customize it for their own editor. From that angle, I think it might be better to make the formats sticky, and allow people to write a plugin that clears the formatting on enter or on double-enter, as they see fit.

Additionally, though, this would be a breaking change.

**Comment by nickschinestzki** [comment]
I have discovered that using `Shift` + `Enter` results in the exact behavior I'm searching for. I'm having difficulties to formulate this into a Plugin, that would not require the user to keep pressing `Shift` to make it work.

**Comment by maliuta-oleksandr** [comment]
the same. it should follow the same styling.

**Comment by vect-spasquereau** [comment]
> I have discovered that using `Shift` + `Enter` results in the exact behavior I'm searching for. I'm having difficulties to formulate this into a Plugin, that would not require the user to keep pressing `Shift` to make it work.

I'm facing the same issue, see [discord thread](https://discord.com/channels/953974421008293909/1075554413587996782/threads/1210630834458206312) 🙂

**Comment by vect-spasquereau** [comment]
thank you very much @Sahejkm 🙌
