### ISSUE TITLE
Bug: Create selection and focus not enabling Cursor

### ISSUE THREAD

**Issue by maliuta-oleksandr** [facebook/lexical#6262]
**Lexical version:  0.13.1**

**I have:**
 - disabled Editor state
 - an event which should trigger Editor to enable editing and set focus(caret) on the last text element. It should work the same as you make double click.
 
I achieved that behavior with dispatching `dblclick`:
```
const event = new MouseEvent('dblclick', {
      view: window,
      bubbles: true,
      cancelable: true
  });
$el.dispatchEvent(event);
const $editor = $el.querySelector('[data-component="text-editor"]') as HTMLElement;
$editor?.dispatchEvent(event);
textEditorPubSub.publish('set-editable', true); // editor.focus();
textEditorPubSub.publish('set-focus'); // textEditorPubSub.publish('set-editable', true);
 
```
But in that case when I continue typing - it creates new text block and that block doesnt extend previous style etc..
I tried to follow with this solution, but it doesnt work, I don't see caret, I still have to double click manually to enable editor.
Is there something I could miss ? 
 ```
 const enableEditingAndSetCaretToTheEnd = useCallback(
        () => {
            editor.update(() => {
                let selection: BaseSelection | RangeSelection | null = $getSelection();
                $getRoot().select();
                editor.focus();

                if (!isEditable) {
                    editor.setEditable(true);
                    selection = $createRangeSelection();
                    (selection as RangeSelection).focus.set('root', $getRoot().getChildrenSize(), 'element');
                }

                const lastTextNode = selection?.getNodes().pop();

                if (lastTextNode && $isTextNode(lastTextNode) && $isRangeSelection(selection)) {
                    lastTextNode.selectEnd();
                }
            });
        },
        [isEditable, editor],
    );
```

**Comment by etrepum** [comment]
You might have better luck getting a response if you post a full reproduction of your problem so that it's easy for other people to observe what is happening and how that differs from what you expect to happen. stackblitz is typically where these are posted. Generally focus and selections don't really "work" in editors that aren't editable because the editor won't reconcile them to the DOM, so you probably want to try marking it editable before you start selecting things.

You're likely losing any style because you're *always* replacing the current selection (`selection = $createRangeSelection();`) instead of preserving any existing selection. The selection stores some metadata about the current style. A non-editable editor can have a selection, but that selection is not reconciled to the DOM until after it becomes editable and an update is reconciled.

**Comment by maliuta-oleksandr** [comment]
@etrepum thanks man, I didn't realise that, we can close this issue )
