### ISSUE TITLE
Bug: Copy/pasting an image from Slack to Lexical does not work

### ISSUE THREAD

**Issue by sagzy** [facebook/lexical#6417]
Lexical version: 0.16.1

## Steps To Reproduce

1. Share a .png file in a Slack channel
2. Right-click and select "Copy image" in Slack
3. Paste the image in the [Lexical playground](https://ghost.slack.com/archives/C02G9E68C/p1721303254228849)

## The current behavior

No image is created.

Screenshot of current behaviour:
![slack_to_lexical](https://github.com/user-attachments/assets/a9358ec5-6c69-4a3a-b353-d2b3be7b4163)

## The expected behavior

Create an image from the copied image from Slack.

Example of expected behaviour from copying an image in Google Images and pasting it in Lexical:
![CleanShot 2024-07-18 at 14 27 54@2x](https://github.com/user-attachments/assets/5f149156-7651-42dc-9e57-e914599b1c99)

**Comment by etrepum** [comment]
Looks like what's happening here is that Lexical prefers text from the clipboard text/html over files. Slack puts the HTML and the file on the clipboard, but the HTML has a reference to Slack's CDN which fails to load due to origin policy and/or session cookies. This could be fixed in your own app by overriding PASTE_COMMAND to have different logic for dispatching DRAG_DROP_PASTE.

This is from `packages/lexical-rich-text/src/index.ts`

```ts
    editor.registerCommand(
      PASTE_COMMAND,
      (event) => {
        const [, files, hasTextContent] = eventFiles(event);
        if (files.length > 0 && !hasTextContent) {
          editor.dispatchCommand(DRAG_DROP_PASTE, files);
          return true;
        }
```

Note that it only considers files if no text content is present.
