### ISSUE TITLE
Bug: "shouldPreserveNewLines" erroneously merges the second node with the above node on conversion back from markdown

### ISSUE THREAD

**Issue by weikequ** [facebook/lexical#6431]
Currently, if `shouldPreserveNewLines` is enabled in `$convertFromMarkdownString` and `$convertToMarkdownString`, Lexical will erroneously merge 2 text nodes into one with a `linebreak` inbetween.
Examples:
- 2 separate paragraph nodes before -> convert to markdown -> convert from markdown -> 1 paragraph node with a newline between
- a quote node followed by a paragraph node -> convert to and from -> 1 quote node with newline inbetween
- a list node followed by a paragraph node -> convert to and from -> 1 list node with 1 listitem node and 2 text nodes with a newline between them

Lexical version: 0.16.1

## Steps To Reproduce

1. Go to the playground
2. Clear editor
3. Turn on setting for "Preserve newlines in markdown"
4. Type "abc" or "> abc" or "- abc"
5. Create a new paragraph underneath with the text "def"
6. Click markdown button
7. Click markdown button again to convert back to rich text
8. See that the 2 separate nodes have erroneously merged into 1 node

## The current behavior

See steps above.

## The expected behavior

Step 8 from the repro steps should have two separate nodes
ie (from the examples above): 
- "abc": 2 separate paragraph nodes
- "> abc": One quote node and one paragraph node
- "- abc": One list node and one paragraph node

Video demos:

https://github.com/user-attachments/assets/858a7f3e-fa8e-4e12-ab82-ae5ec24a02af

https://github.com/user-attachments/assets/b9623f6e-1ebb-46c8-88c0-2bc46ff8f849

## Impact of fix

Bug makes the state of converting to and from markdown inconsistent and unpredictable, making it incredibly difficult to use the functionality. Every single user of the markdown plugin with `shouldPreserveNewLines` enabled would be affected.

**Comment by potatowagon** [comment]
the initial markdown implementation is new line delimited, and ignores extra new lines. in order to achieve a preserve new lines option, a tradeoff have to be made which is to break away from that and not use new lines as delimiter: 

https://github.com/facebook/lexical/blob/3a96788a2d01f7953d0a3bc954b59f91bf7ceb47/packages/lexical-markdown/src/MarkdownExport.ts#L35

the side effect of this is new lines will not be inserted between block nodes during export, in order to preserve the number of new lines

to solve your issue, u can set `shouldPreserveNewLines` to false and your implementation will have new line delimited nodes and be more aligned with markdown spec

**Comment by weikequ** [comment]
Hi, thanks for responding! Do you know if there's a way to both preserve new lines as well as have the correct behavior shown above? I think this is still a bug, as having 2 nodes of different types be merged into 1 node does not seem like intended behavior.
