### ISSUE TITLE
Bug: DecoratorNodes no longer allowed at the root?

### ISSUE THREAD

**Issue by irahopkinson** [facebook/lexical#6451]
Previously in the docs (~v0.12) I read that the root node can have either element nodes or decorator nodes. I can't find that in the docs now. I'm now on the latest Lexical v0.16.1, when I click on a decorator node I have at the root I get this error: 
```console
Error: Children of root nodes must be elements
    at <MyDecoratorNode>.getTopLevelElement
```  

Indeed `getTopLevelElement` in `LexicalNode` gives that error  https://github.com/facebook/lexical/blob/ebc8d669fcd7ccc9f0e550be360056787e6722a0/packages/lexical/src/LexicalNode.ts#L356-L359

Lexical version: v0.16.1

## Steps To Reproduce

1. Use the CodeSandbox link below.
2. Click on the chapter marked as '1' in the editor.
3. The error above is displayed.

Link to code example:

https://codesandbox.io/p/sandbox/decorator-in-root-h46skq?file=%2Fsrc%2FEditor.tsx

## The current behavior
The error above is displayed.

## The expected behavior
No error is displayed.

## Impact of fix
It's currently confusing that you can have a `DecoratorNode` at the root but when you try to do something with it produces an error.

If it's really intended that a `DecoratorNode` can't be at the root then when loading editor state it should error if there is a `DecoratorNode` at the root.

**Comment by etrepum** [comment]
I think this is a combination of a few things:

1. `DecoratorNode` can be a child of `RootNode`
2. `LexicalNode.getTopLevelElement` is expected to always return an `ElementNode`, this is clear from the name and the type (both in flow and typescript)
3. `node.getTopLevelElement()` is called in some places without consideration for the edge case that `DecoratorNode` can be a child of `RootNode`

The fix for this is one of:

1. Change `getTopLevelElement` to not always return an `ElementNode` (this was the legacy behavior, which caused other bugs, but were not detected easily because the types also used to be very broken). It may be possible to do this with better types, but the LexicalNode implementation has to be the widest version (e.g. `DecoratorNode | ElementNode`)
2. Change the code currently using `getTopLevelElement` to handle this `DecoratorNode` edge case specifically before calling `getTopLevelElement`
3. Add a new method that is largely similar to `getTopLevelElement` but handles this edge case, and change the code to use that method instead.

In most cases it's desirable for `getTopLevelElement` to only return an `ElementNode`, e.g. if you're calling it from a `TextNode` or an `ElementNode` you don't want to have to handle the semantically impossible case of a `DecoratorNode`.

**Comment by irahopkinson** [comment]
@etrepum thanks for that good clarification of the issue. I was thinking of making a PR for item 1 today but 3 would also work to create a `getTopLevelNode` method. I could create a PR if there was some direction on this from the Lexical team?

**Comment by irahopkinson** [comment]
@etrepum thanks for the quick fix!
