### ISSUE TITLE
Bug: n.matchAll is not a function. (In 'n.matchAll(/\S+/g)', 'n.matchAll' is undefined)

### ISSUE THREAD

**Issue by akichim21** [facebook/lexical#6461]
Lexical version: 0.16.1

## Steps To Reproduce
![スクリーンショット 2024-07-26 11 35 29](https://github.com/user-attachments/assets/a5902c2e-1918-4da5-a103-45bdcd968e4a)
* Rarely an error occurs.

## The current behavior
* n.matchAll is not a function. (In 'n.matchAll(/\S+/g)', 'n.matchAll' is undefined)
  - IPad
  - Google 160.0.373863126
  - iOS 12.5

* n.matchAll(...) is not a function or its return value is not iterable
  - Windows
  - Chrome 71.0.3578

## The expected behavior
no error

**Comment by etrepum** [comment]
String.prototype.matchAll is only used in one place (outside of tests) in the internal function `normalizeClassNames`. Something in your code is likely causing this by passing in the wrong type, but it's hard to say what exactly since you didn't provide any reproduction instructions. I'd start looking at the theme configuration and any custom nodes that you have that might be using `normalizeClassNames` indirectly (such as `addClassNamesToElement` or `removeClassNamesFromElement`)

**Comment by akichim21** [comment]
thank you for your response @etrepum .
We use addClassNamesToElement, we check this code.
