### ISSUE TITLE
Feature: Scroll for table

### ISSUE THREAD

**Issue by denindka** [facebook/lexical#6480]
## Description

It would be great if the table had its own scroll bar. Right now, the scroll affects the entire document, which is not very convenient.
The video shows an example of how this is implemented in other projects.

https://github.com/user-attachments/assets/00519b81-a211-4d6f-bfe8-824a99980b9a

**Comment by keiseiTi** [comment]
I tried to solve this problem, but the createDOM method of ElementNode does not support nested elements 
<img width="850" alt="image" src="https://github.com/user-attachments/assets/7ebbf0f4-a43f-4f2c-a49a-b138e7f81fa8">

**Comment by keiseiTi** [comment]
Can ElementNode add a method createDOMContainer to create a DOM container that wraps the DOM ? @zurfyx

**Comment by agscripter** [comment]
Hey, It would be great to have this feature. +1

**Comment by lxzmo** [comment]
+1

**Comment by bilobom** [comment]
+1

**Comment by alphaCastor** [comment]
As quick workaround (before we will have nested elements support) you can use css:
```css
table {
  width: 100%;
  overflow: auto;
  display: block;
}
```
And keep in mind that whole editor container must have `width`

**Comment by CojocaruCristi** [comment]
+

**Comment by CojocaruCristi** [comment]
+++++++

**Comment by MaslovRustislav** [comment]
Fell into the same issue, please help!

**Comment by yaojiu19** [comment]
I am trying to solve it by customElements,  but were some issues. pr: #6587

**Comment by GermanJablo** [comment]
Thanks to @yaojiu19 for offering to contribute to this issue, although that PR doesn't solve the problem in "the lexical way" as the maintainers mentioned there.

I'm willing to solve this issue myself, but first I'd like to know if the Lexical team thinks it's ok to introduce a new ElementNode that acts as a wrapper.

**Comment by etrepum** [comment]
@GermanJablo The biggest problems with #6587 are that there are exactly zero lines of tests, documentation or examples. There's no way to know whether it works at all other than to fill in all the missing pieces. Does it say it solves a problem? Sure. Does it actually? Does it break anything for people who are using custom nodes with however Lexical interacts with them today? Who knows. Can't possibly approve it in its current state.

Custom elements aren't used or tested anywhere else in Lexical, and that it's unclear there wouldn't be other problems with this approach (regarding selection, events, or anything else). A different approach that did not add custom elements was in #5930 / #5981 but that also stalled in part because you questioned what utility it would have, so it too is missing all of the finishing work that would have to be done before anyone knows if it is a real solution or not.

**Comment by GermanJablo** [comment]
I don’t see why I would be responsible for PR 5930 being stalled. If that's the case for some reason, I encourage anyone who wants to continue it :)

As far as this issue is concerned, what I am suggesting is adding a new ElementNode, which seems to me to be the simplest solution.

**Comment by etrepum** [comment]
I'm sure the large part that it's just a hard problem to solve, but your feedback on that PR was the only negative feedback and may have contributed to them losing steam. Adding a new kind of ElementNode that has components that are otherwise "invisible" to the reconciler is more or less equivalent to having a DecoratorElementNode, so going back to that PR and looking more closely might be worth your time. Note that any decorator can render all of its children directly in createDOM/updateDOM and return null from its decorate method if there isn't a need for a framework managed portal. I look forward to seeing what you come up with!

**Comment by GermanJablo** [comment]
I have opened a PR that closes this issue: https://github.com/facebook/lexical/pull/6713.
Comments and observations are welcome.

**Comment by agscripter** [comment]
Hi @GermanJablo, great job, I love this feature.

Do you believe it's possible to have a table inside the document that its width is larger than the document and the table can be shown like in Quip:

<img width="1348" alt="Screenshot 2024-10-17 at 8 11 00 AM" src="https://github.com/user-attachments/assets/6c726780-38a4-4864-a31c-cba713e11cc8">

As you can see, the table width is larger than the document content, but still the table is shown without the horizontal scroll.
Perhaps with your implementation it's possible to achieve this result as well.

**Comment by GermanJablo** [comment]
Thanks @agscripter. Yes, that should be possible by playing with the paddings

**Comment by yaojiu19** [comment]
now I implement it through plugins
![PixPin_2024-10-18_09-11-39](https://github.com/user-attachments/assets/955b89a0-92b9-4b7d-82e2-32a78857cc2e)

create a scrollbar outside the editor by watch the width and root element of the table
