### ISSUE TITLE
Feature: TablePlugin support to change borderStyle and borderWidth

### ISSUE THREAD

**Issue by tyy11017** [facebook/lexical#6564]

**Comment by turnerguo** [comment]
I think this kind of specific requirements should be simply use [Lexical Theming](https://lexical.dev/docs/getting-started/theming) but not a table feature.

**Comment by etrepum** [comment]
Yes, generally these sorts of customizations can be added by subclassing the node to add extra properties that can be rendered in when overriding createDOM/updateDOM/exportDOM. A node override should be used so that all existing code that is expecting TableNode will work with your custom table implementation
