### ISSUE TITLE
Bug: Crashes when navigating within a table with merged cells

### ISSUE THREAD

**Issue by Shubhankerism** [facebook/lexical#6584]
In some cases of tables with merged cells, on moving the cursor within the table using arrow keys, we can see some crashes.

Lexical version: 0.17.1

## Steps To Reproduce

1. Paste a table
2. Move cursor inside the table
3. Use right arrow key to move the cursor 
![nav-merge-cells-issue](https://github.com/user-attachments/assets/65973f81-298f-4c60-9b38-c44e790db2a8)

HTML for one such table for which we can see crashes: https://gist.github.com/Shubhankerism/9503d92c7d87a126557091c8240c63d3

## The current behavior
We can see the crash.

## The expected behavior
To not crash and cursor moves correctly between cells

**Comment by etrepum** [comment]
This one has something to do with the TableMap being computed incorrectly. My understanding is that it should always be square? I added a conditional breakpoint to `isExitingCell` with `!firstCell || !lastCell` as the condition

If I were fixing this class of issues, I would refactor TableMap into a class with methods that do the right things (w/ invariants) rather than trying to work directly with an array of arrays. The typescript settings we use make it very easy to skip bounds checks and have these sorts of runtime errors when you are using array indexing directly.

```
> tableMap
(5) [Array(5), Array(5), Array(5), Array(5), Array(1)]
```

**Comment by etrepum** [comment]
The problem with this table is that it's not rectangular, the code assumes that the table is rectangular
