### ISSUE TITLE
Bug: Pasting into custom inline ElementNode fails

### ISSUE THREAD

**Issue by nigelgutzmann** [facebook/lexical#6701]
Lexical version: 0.18.0

## Steps To Reproduce

1. Create a custom ElementNode, which has `isInline() { return true; }`
2. Paste content into the custom ElementNode
3. The paste fails with error message `Cannot use 'in' operator to search for '__language' in null`

And a video of me pressing "ctrl-v" to paste some text into the CustomElementNode: https://youtu.be/XJHWj9TZXIg

Link to code example: https://stackblitz.com/edit/facebook-lexical-urixtg?file=src%2FCustomElementNode.ts

## The current behavior
The paste fails with error message `Cannot use 'in' operator to search for '__language' in null`

## The expected behavior
The content is inserted into the custom ElementNode

## Impact of fix
You cannot paste into inline ElementNodes. At Lumen5, we are using inline ElementNodes to wrap groups of words together to demonstrate relationships between the words and other objects in the DOM. There are millions of users.

**Comment by etrepum** [comment]
There are four issues here:

1. Every child of the root is required to be a block node (not inline)
2. There's a non-null assertion (`!`) that assumes the first condition to be true, when it should be a runtime invariant
3. That particular runtime type check is written in the wrong order (the `$isElementNode` check should be first) but it wasn't caught because of 2
4. RangeSelection does not support inserting into inline ElementNode

If you fix 1, the runtime error caused by the combination of 2 & 3 goes away, but the insertion point is after the inline node.

It should probably be allowed for an inline ElementNode to have other inline nodes as children and the paste should allow for that to happen, unclear what the right strategy would be if there were block nodes to be inserted.

/cc @zurfyx

**Comment by nigelgutzmann** [comment]
@etrepum thanks so much for your speedy help! Amazing!

I did not realize that it was a requirement for every child of the root to be a block node. Perhaps there's a way to give an error message in case someone adds a non-block child to the root (like me! haha)?

Or maybe that should be added to the documentation somewhere?

**Comment by etrepum** [comment]
Documentation certainly makes sense. The block/inline/etc. stuff is a bit messy and I don't currently quite understand it all myself because there isn't documentation and most of that code and those decisions predate my usage of lexical.

There are situations where you might want to temporarily allow inline nodes to be inserted into the root which are then fixed up by node transforms before it really matters, plus there would be a performance impact of that runtime check, so I don't think it that immediate error messages are likely, but once you get to this point (inserting into an inline node with no block parent) an invariant makes a lot more sense than a non-null type assertion.
