### ISSUE TITLE
Bug: use PASTE_COMMAND command lost some style

### ISSUE THREAD

**Issue by SD-Gaming** [facebook/lexical#6720]
use PASTE_COMMAND command lost some style

Lexical version: 0.18.0

## Steps To Reproduce

1. open lexical playground and open use lexical context menu
2. clean all text, and input any text
3. select the text, click the font-size plus button, and see the text is larger
4. copy the larger text, and use the context menu to paste
5. see the new paste text

## The current behavior
The new text is small
## The expected behavior
new text is equal to the copied text font size
## Impact of fix
It can reproduce every time.

**Comment by citruscai** [comment]
i would like to take on this issue!!

**Comment by citruscai** [comment]
# update

realized this could be the main problem in why context menu isn't pasting the formatting. isTrusted is being marked as false. could it be a permission problem? when i do ctrl+v isTrusted is marked as true. think im getting closer to solving the problem
![image](https://github.com/user-attachments/assets/ae7e2064-564e-4b86-aebd-34db35ce08a6)

**Comment by etrepum** [comment]
It's happening for two reasons, both of these issues can be fixed but fixing either of them would solve this particular issue:

1. The async clipboard API, used by this paste command, does not support the lexical `application/x-lexical-editor` format because it's not on the clipboard as a  [web custom format](https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api)
2. Lexical does not properly import the style of the text that it exported when parsing the HTML (it can access the sanitized text/plain and text/html formats on the clipboard and chooses the text/html data)

**Comment by citruscai** [comment]
> It's happening for two reasons, both of these issues can be fixed but fixing either of them would solve this particular issue:
> 
> 1. The async clipboard API, used by this paste command, does not support the lexical `application/x-lexical-editor` format because it's not on the clipboard as a  [web custom format](https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api)
> 2. Lexical does not properly import the style of the text that it exported when parsing the HTML (it can access the sanitized text/plain and text/html formats on the clipboard and chooses the text/html data)

ok i will try each of these and give you update! ty so much for help
