### ISSUE TITLE
Bug: How can i add className insted of style property in dispatchCommand for text alignment

### ISSUE THREAD

**Issue by MahmoudAdel9** [facebook/lexical#6850]
How to add add className insted of style property in dispatchCommand for text alignment

this is my code
case RichTextAction.LeftAlign: {
            editor.dispatchCommand(FORMAT_ELEMENT_COMMAND, 'left');
            break;
          }

**Comment by etrepum** [comment]
You can't, that's not how these nodes work. If you want to change how they work, you will have to subclass each ElementNode that you want to use classes instead of styles and then override the methods to work as you want them to (createDOM and updateDOM, maybe also exportDOM and importDOM). Then you would use node overrides to use your nodes instead of the default implementations. This must be done separately for each ElementNode in your editor.
