### ISSUE TITLE
Bug: $getSelection returns null in editor.update while it returns a result in editor.read

### ISSUE THREAD

**Issue by skrivle** [facebook/lexical#6885]
Lexical version: 0.20.0

## Steps To Reproduce

1. go to https://codesandbox.io/p/sandbox/grmcty
2. type in editor
3. tab to next textfield (this is important)
4. click button
5. inspect console.log => observe different result for $getSelection from read and update

Note: this only happens when the promise resolves with a delay. When resolving right away, it seems to be working correctly. 

Link to code example: https://codesandbox.io/p/sandbox/grmcty

## The current behavior
$getSelection returns `null` when called in an update from a promise handler while it returns a result when called from read

## The expected behavior
$getSelection returns the same result when called from read or update?

## Impact of fix

Happens always... we have found a solution where we nest an update in a read function but we'd like to keep it clean by just using update. 🙏 . The current behavior seems inconsistent

**Comment by etrepum** [comment]
The reason this happens is because editor.update reconciles the selection from the DOM before the update begins, if it is a RangeSelection, where editor.read does not do that unless there are pending updates to reconcile. The DOM selection is on the button, not in the document, so it sets the selection to null.

What you probably want to do is use editor.update but with `$getSelection() || $getPreviousSelection()` instead of just `$getSelection()`.

**Comment by skrivle** [comment]
Hi, thank you very much for the quick response and feedback! I can confirm this approach works. 

I do like to point out this only happens when focus is moved to an `<input type='text'/>` field. I we were to focus the button immediately after the Lexical text box, $getSelection() would still return a result. Though, I guess this still makes sense given your explanation.

🙏
