### ISSUE TITLE
Bug: $generateNodesFromDOM the API is very strange and nonintuitive

### ISSUE THREAD

**Issue by croraf** [facebook/lexical#6985]
Lexical version: 0.18.0

## Steps To Reproduce

1. Check this documentation https://lexical.dev/docs/packages/lexical-html#importing
2. It is so strange, nonintuitive and unexplained why `$generateNodesFromDOM(editor, dom)` needs editor as a first argument. It needs to create `nodes` from the provided `dom` which is later to be added to an editor. The confusion is nicely visible in the second snipped on the given link, where first you get the nodes from the editor and only after you create that same editor.

## The expected behavior

`$generateNodesFromDOM(editor, dom)`  should only accept one argument: `dom`

**Comment by etrepum** [comment]
The editor argument is needed because the editor configuration is required to generate DOM. It's not possible to call $getEditor from editor.getEditorState().read unless the newer editor option is passed to that function or editor.read is used. There are no plans to change this function's call signature for backwards compatibility and historical reasons.
