### ISSUE TITLE
Expose ImageNode

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#819]
ImageNode could be pretty useful for Outline users building, for instance, email composers. 

Let's polish it up Image and expose it as an extension in core and as a hook in outline-react.

**Comment by thegreatercurve** [comment]
Closing this for the moment as the image upload capability has since been added, and resizing has been improved.

**Comment by acywatson** [comment]
People in the community have expressed an interest in this - reopening so we can consider exposing it

**Comment by trueadm** [comment]
I feel like exposing ImageNode doesn't really work too well due to the fact many apps/websites that use Lexical will typically have their own UI design system or component system and thus probably wouldn't work too well with ImageNodes. Especially, as the example ImageNode on the playground doesn't support many features that purpose built systems would offer. I guess we can keep this open for now, but I struggle to see how we might expose this on npm without it needing to support a bunch of features to make it work in different apps.

**Comment by EgonBolton** [comment]
Hello! I think there is a lot of recyclable logic for those who want to use this plugin.

Some thoughts:

I have opened an issue in this line some time ago regarding the caption: https://github.com/facebook/lexical/issues/3172
This would avoid having to do a lot of internal surgery to the plugin if someone doesn't want to use, for example, mentions in the caption.

I think the same could be done with the UI. Perhaps offer one by default but one that can be overridden as a property of <ImagePlugin decorate={ ... }> . So for example someone using Nextjs could use the <Image> component.

**Comment by moyang-pro** [comment]
When to make ImageNode as well as TextNode

**Comment by acywatson** [comment]
We're not supporting this anytime soon
